<?php
defined('BASEPATH') OR exit('No direct script access allowed');
?>
<!-- Bootstrap core CSS-->
<link href="<?php echo base_url(); ?>assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

<!-- Custom fonts for this template-->
<link href="<?php echo base_url(); ?>assets/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

<!-- Page level plugin CSS-->
<link href="<?php echo base_url(); ?>assets/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">

 <script src="<?php echo base_url(); ?>assets/vendor/jquery/jquery.min.js"></script>
 <script src="<?php echo base_url(); ?>assets/js/typeahead.js"></script>


<!-- Custom styles for this template-->
<link href="<?php echo base_url(); ?>assets/css/sb-admin.css" rel="stylesheet">
<link href="<?php echo base_url(); ?>assets/css/style.css" rel="stylesheet">

<script src="<?php echo base_url(); ?>assets/js/bootstrap-datetimepicker.min.js"></script>
<link href="<?php echo base_url(); ?>assets/css/bootstrap-datepicker3.css" rel="stylesheet"> 
<script src="<?php echo base_url(); ?>/assets/js/jquery.validate.min.js"></script>
<script src="<?php echo base_url(); ?>/assets/js/common.js"></script>
<div class="container-fluid">
		
	
	<div style="text-align:center;"><input type="button" onclick="printDiv('printableArea')" value="print" /></div>
	<style>
		.quote_view p{margin-bottom:0px;}
		
		.borderbox{border:2px solid black;}
		.quote_view .border_left{border-left:2px solid black;}
		.quote_view .border_right{border-right:2px solid black;}
		.quote_view .border_bottom{border-bottom:2px solid black;}
		.quote_view .border_top{border-top:2px solid black;}
		
		table {
			table-layout:fixed;
		}
		
		.table-bordered td{
			border: 0px solid black;			
		}
		
		.space_bottom{margin-bottom:15px;}
		.card{border:0px solid rgba(0,0,0,.125) !important;}
	</style>
	<div class="card mb-3" id="printableArea">
		<div style="width:100%;padding-top:30px;padding-bottom:50px;">
			<div style="width:100%;text-align:center;"><img src="<?php echo base_url(); ?>/assets/img/logo.png"></div>	
		</div>
		
		<div class="card-body">
			<h3 style="width:100%;text-align:left;">Order In Process<span style="float:right"><?php echo getQuotationNo($ordersInfo->quotation_id); ?> / <?php echo getOrderNo($ordersInfo->order_id); ?></span></h3>
			<div class="row quote_view borderbox" style="border: 2px solid black;font-size: 21px;">
				<div class="col-sm-6 border_right" style="border-right:2px solid black;">
					<p style="margin-bottom:0px;"><b>Exporter:</b></p>
					<p style="margin-bottom:0px;"><b>TARUN ENTERPRISES</b></p>
					<p style="margin-bottom:0px;"><?php echo $ordersInfo->store_address; ?></p>
					<p style="margin-bottom:0px;">Phone: <?php echo $ordersInfo->store_phone; ?></p>
					<p style="margin-bottom:0px;">Email: <?php echo $ordersInfo->store_email; ?></p>
					<p style="margin-bottom:0px;">GST No: <?php echo $ordersInfo->store_gst_no; ?></p>
					<?php if($ordersInfo->store_name == 'Allahabad'){  ?>
						<p style="margin-bottom:0px;">Drug Licence: <?php echo $ordersInfo->drug_licence_no; ?></p>
						<p style="margin-bottom:0px;">Dt. <?php echo $ordersInfo->drug_date; ?></p>
					<?php } else { ?>
						<p style="margin-bottom:0px;">&nbsp;&nbsp;</p>
						
					<?php } ?>					
				</div>
				<div class="col-sm-6">
					<div class="row">
						<div class="col-sm-6 border_right border_bottom" style="border-right:2px solid black;border-bottom:2px solid black;">
							<p style="margin-bottom: 5px;" ><b>Order No:</b></p>
							<p style="margin-bottom: 15px;"><?php echo getOrderNo($ordersInfo->order_id); ?></p>
						</div>
						<div class="col-sm-6 border_bottom" style="border-bottom:2px solid black;">
							<p style="margin-bottom: 5px;"><b>Order Date:</b></p>
							<p style="margin-bottom: 15px;"><?php echo date('F, d, Y', strtotime($ordersInfo->order_date)); ?></p>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-6 border_right border_bottom" style="border-right:2px solid black;border-bottom:2px solid black;">
							<p style="margin-bottom: 5px;"><b>Issued From:</b></p>
							<p style="margin-bottom: 15px;"><?php echo $ordersInfo->store_name; ?></p>
							
						</div>
						<div class="col-sm-6 border_bottom" style="border-bottom:2px solid black;">
							<p style="margin-bottom: 5px;"><b>Currency:</b></p>
							<p style="margin-bottom: 15px;"><?php echo $ordersInfo->currency; ?></p>
							
						</div>
					</div>
					<div class="row">
						<div class="col-sm-6 border_right " style="border-right:2px solid black;">
							<p style="margin-bottom: 5px;"><b>Insurance:</b></p>
							<p style="margin-bottom: 15px;"><?php echo $ordersInfo->insurance; ?></p>
						</div>
						<div class="col-sm-6 ">
							<p style="margin-bottom: 5px;"><b>Generated by:</b></p>
							<p style="margin-bottom: 15px;"><?php echo $ordersInfo->firstname .' '.$ordersInfo->lastname; ?></p>
						</div>
					</div>
				</div>
				
				<div class="col-sm-6 border_top border_right" style="border-right:2px solid black;border-top:2px solid black;">
					<p style="margin-bottom:0px;"><b>Customer(Bill to):</b></p>
					<?php $billingAddress=nl2br($ordersInfo->billing_details);
						while(preg_match("/(.*?)\n/is",$billingAddress,$matcher)){
							print "<b>$matcher[1]</b>";
							$billingAddress=after($matcher[0],$billingAddress);
							break;
						}
					?>
					<?php echo $billingAddress; ?>
					<?php if($customerInfo->gst){ ?>
					<p style="margin-bottom:0px;">GST No.: <?php echo $customerInfo->gst; ?></p>
					<?php } ?>
					<?php if($customerInfo->company_registration_no){ ?>
					<p style="margin-bottom:0px;">Reg. No.: <?php echo $customerInfo->company_registration_no; ?></p>
					<?php } ?>
					<?php if($customerInfo->drug_licence_no){ ?>
					<p style="margin-bottom:0px;">Drug Licence no.: <?php echo $customerInfo->drug_licence_no; ?></p>
					<?php } ?>	
				</div>
				
				<div class="col-sm-6 border_top" style="border-top:2px solid black;">
					<p style="margin-bottom:0px;"><b>Consingee(Ship to):</b></p>					
					<?php $shippingAddress=nl2br($ordersInfo->shipping_details);
						while(preg_match("/(.*?)\n/is",$shippingAddress,$matcher)){
							print "<b>$matcher[1]</b>";
							$shippingAddress=after($matcher[0],$shippingAddress);
							break;
						}
					?>
					<?php echo $shippingAddress; ?>
					<?php if($customerInfo->gst){ ?>
					<p style="margin-bottom:0px;">GST No.: <?php echo $customerInfo->gst; ?></p>
					<?php } ?>
					<?php if($customerInfo->company_registration_no){ ?>
					<p style="margin-bottom:0px;">Reg. No.: <?php echo $customerInfo->company_registration_no; ?></p>
					<?php } ?>	
					<?php if($customerInfo->drug_licence_no){ ?>
					<p style="margin-bottom:0px;">Drug Licence no.: <?php echo $customerInfo->drug_licence_no; ?></p>
					<?php } ?>	
				</div>
				
				<!-- <div class="col-sm-6 border_top border_right border_bottom" style="border-top:2px solid black;border-right:2px solid black;border-bottom:2px solid black;"> -->
				<?php
					$delivery = str_word_count($quotationInfo->delivery);
					$payment_terms = str_word_count($quotationInfo->payment_terms);
					$x=0;
					$y=0;
					if($delivery > $payment_terms){
						$x=2;
					} else if($payment_terms > $delivery) {
						$y=2;
					} else {
						$x = 2;
					}
				?>			
				<div class="col-sm-6 border_right" style="border-right:2px solid black;border-top:2px solid black;border-right:2px solid black;">
					<p style="margin-bottom: 0px;"><b>Terms of Delivery:</b></p>
					<p style="margin-bottom: 0px;"><?php echo $ordersInfo->delivery; ?></p>
				</div>
				<div class="col-sm-6" style="border-top:2px solid black;">
					<p style="margin-bottom: 0px;"><b>Terms of Payments:</b></p>
					<p style="margin-bottom: 0px;"><?php echo $ordersInfo->payment_terms; ?></p>
				</div>
					
				
				<div class="col-sm-12 border_top border_bottom" style="border-top:2px solid black;border-bottom:2px solid black;">
					<p style="margin-bottom: 0px;"><b>Terms & Conditions:</b></p>
					<p style="margin-bottom: 0px;"><?php echo $ordersInfo->terms_conditions; ?></p>
				</div>
				
				<div class="col-sm-12 border_bottom" style="border-top:0px solid black;border-bottom:2px solid black;">
					<p style="margin-bottom: 0px;"><b>Special instruction:</b></p>
					<p style="margin-bottom: 0px;"><?php echo $ordersInfo->special_instruction; ?></p>
				</div>
				
				<table class="table-sm" id="protable" width="100%" cellspacing="0" style="font-size: 21px;">
					<tr>
						<th class="border_right" style="width:4%;border-right:2px solid black;">S.N.</th>
						<th class="border_right" style="width:46.3%;border-right:2px solid black;">Product Description</th>
						<th class="border_right" style="width:8.5%;border-right:2px solid black;text-align:center;">HSN</th>
						<th class="border_right" style="width:6%;border-right:2px solid black;text-align:center;">Qty</th>
						<th class="border_right" style="width:6%;border-right:2px solid black;text-align:center;">Unit</th>
						<th class="border_right" style="width:6%;border-right:2px solid black;text-align:center;">Rate</th>
						<th class="border_right" style="width:10%;border-right:2px solid black;text-align:center;">Disc(Per Unit)</th>
						<th style="width:12%;text-align:right;">Net Amount</th>
					</tr>
					
					<?php
						$net_total = 0;
						$i=1;
						foreach($orderProducts as $orderProduct){ 
							$net_total = $net_total + $orderProduct['net_amount'];					
					?>						
						<tr class="prtr" data-val="<?php echo $orderProduct['prod_id'];?>">
							<td class=" " style="border-right:2px solid black;border-top:2px solid black;"><?php echo $i; ?></td>
							<td class=" " style="border-right:2px solid black;border-top:2px solid black;"><b> <?php echo $orderProduct['model_name']; ?> </b> | <?php echo $orderProduct['description']; ?></td>
							<td align="center" style="border-right:2px solid black;border-top:2px solid black;"><?php echo $orderProduct['hsn']; ?></td>
							<td align="center" style="border-right:2px solid black;border-top:2px solid black;"><?php echo $orderProduct['qty']; ?></td>
							<td align="center" style="border-right:2px solid black;border-top:2px solid black;"><?php echo $orderProduct['unit']; ?></td>
							<td align="center" style="border-right:2px solid black;border-top:2px solid black;"><?php echo number_format((float)$orderProduct['rate'], 4, '.', ''); ?></td>
							<td align="center" style="border-right:2px solid black;border-top:2px solid black;"><?php echo number_format((float)$orderProduct['discount'], 4, '.', ''); ?></td>
							<td class="" style="border-top:2px solid black;" align="right"><?php echo number_format((float)$orderProduct['net_amount'], 2, '.', ''); ?></td>
						</tr>
					
					<?php $i++; } ?>					
					<tr class="nettottr">
						<td class=" " style="border-right:2px solid black;border-top:2px solid black;" colspan="7" align="right" ><b>Net Total</b></td>
						<td class=" " style="border-top:2px solid black;" align="right"> <i class="<?php echo $ordersInfo->currency_faclass; ?>" style="font-size:13px;"></i>&nbsp; <span id="net_total"><?php echo number_format((float)$net_total, 2, '.', ''); ?></span></td>
					</tr>
					<tr class="ftr">
						<td class=" " style="border-right:2px solid black;border-top:2px solid black;" colspan="7" align="right" ><b>Freight Charges</b></td>
						<td class=" " style="border-top:2px solid black;" align="right"> <i class="<?php echo $ordersInfo->currency_faclass; ?>" style="font-size:13px;"></i>&nbsp; 
						<span id="freight_charge"><?php echo number_format((float)$ordersInfo->freight_charge, 2, '.', ''); ?></span></td>
					</tr>
							<?php
								if($ordersInfo->currency == 'INR'){
								if($productgst){ 
								$totwithgst = 0;
								$freight_charge = $ordersInfo->freight_charge;
								foreach($productgst as $progst){
								$perProFrch = ($freight_charge / $net_total) * $progst['net_amount'];
								$perProFrchWthGst = ($perProFrch * $progst['product_gst']/100);
								$totgst = $perProFrchWthGst + ($progst['net_amount'] * $progst['product_gst']/100);								
								$totwithgst = $totwithgst + $totgst;
							?>
						
							<tr>
								<td class="" style="border-right:2px solid black;border-top:2px solid black;" colspan="7" align="right" ><b>GST @ <?php echo $progst['product_gst']; ?>%</b></td>
								<td class="" style="border-top:2px solid black;" align="right"> <i class="<?php echo $ordersInfo->currency_faclass; ?>" style="font-size:13px;"></i>&nbsp; <?php echo number_format((float)$totgst, 2, '.', ''); ?></td>
							</tr>
						<?php } ?>
						<?php } ?>
						<?php } ?>
					<tr class="grndtr">
						<td class=" " style="border-right:2px solid black;border-top:2px solid black;border-bottom:0px solid black;" colspan="7" align="right" ><b>Grand Total</b></td>
						<td class=" " style="black;border-top:2px solid black;border-bottom:0px solid black;" align="right"> <b><i class="<?php echo $ordersInfo->currency_faclass; ?>" style="font-size:13px;"></i>&nbsp; <span id="grand_total"><?php echo number_format((float)($net_total + $ordersInfo->freight_charge + $totwithgst), 2, '.', ''); ?></span></b></td>
					</tr>
				</table>
			</div>
			<br>
			<div class="row">
					<div class="col-sm-12" style="padding-right: 0px;padding-left: 0px;">
						<p style="margin: 0px;">Greetings!<br>
Thank you for your valued order. Same is under process. We request you to please check all the details as above and arrange payment as per banking details below. In case you wish to use online payment , please use our payment gateway at our website <a href="http://www.optitecheyecare.com/payment.php">www.optitecheyecare.com/payment.php</a> .</p> 
						<p style="margin: 0px;"></p>							
					</div>					
				</div>
				<br>
				<div class="row">
					<div class="col-sm-12" style="padding-right: 0px;padding-left: 0px;">
						<p style="margin: 0px;">Remit to:</p>
					</div>
					
					<div class="col-sm-6" style="padding-right: 0px;padding-left: 0px;">					
						<div style="width:100%;float:left;">
							<p style="margin: 0px;width:40%;float:left;"><b>Payment :</b></p><p style="margin: 0px;float:left;">100% T/T(wire)</p>
						</div>	
						<div style="width:100%;float:left;">
							<p style="margin: 0px;width:40%;float:left;"><b>Beneficiary's Name:</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->beneficiary_name; ?></p>
						</div>
						
						<div style="width:100%;float:left;">
							<p style="margin: 0px;width:40%;float:left;"><b>Bank Name:</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->bank_name; ?></p>
						</div>
						
					</div>
					
					<div class="col-sm-6" style="padding-right: 0px;padding-left: 0px;">					
						<div style="width:100%;float:left;">
							<p style="margin: 0px;width:40%;float:left;"><b>Bank Details for</b></p><p style="margin: 0px;float:left;"> (<?php echo $ordersInfo->currency; ?>)</p>
						</div>	
						<div style="width:100%;float:left;">	
							<p style="margin: 0px;width:40%;float:left;"><b>Account No.:</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->account_number; ?></p>
						</div>
						
						<?php if($ordersInfo->currency == 'INR'){ ?>
							<?php if(!empty($bankInfo->ifsc_code)){ ?>
								<div style="width:100%;float:left;">
									<p style="margin: 0px;width:40%;float:left;"><b>IFSC Code :</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->ifsc_code; ?></p>
								</div>
							<?php } ?>
						<?php } else { ?>						
							<?php if(!empty($bankInfo->swift_code)){ ?>
								<div style="width:100%;float:left;">
									<p style="margin: 0px;width:40%;float:left;"><b>SWIFT Code :</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->swift_code; ?></p>
								</div>
							<?php } ?>	
						<?php } ?>						
					</div>
					
					<div class="col-sm-12" style="padding-right: 0px;padding-left: 0px;">					
						<div style="width:100%;float:left;">
							<p style="margin: 0px;width:20%;float:left;"><b>Bank Address :</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->bank_address; ?></p>
						</div>										
					</div>				
				
					<div class="col-sm-12" style="padding-right: 0px;padding-left: 0px;">						
						<p style="margin: 0px;">Bank remittance charge shall be paid by payer(buyer)</p><br>
						<p style="margin: 0px;">For Tarun Enterprises</p><br><br>
						<p style="margin: 0px;">Order Processing Team</p><br>
						<p style="margin: 0px;font-size:14px;">Created by (<?php echo $ordersInfo->firstname .' '.$ordersInfo->lastname; ?>)</p> 
					</div>					
				</div>
		</div>		
	</div>	
</div>
<script>
function printDiv(divName) {
     var printContents = document.getElementById(divName).innerHTML;
     var originalContents = document.body.innerHTML;

     document.body.innerHTML = printContents;

     window.print();

     document.body.innerHTML = originalContents;
}
</script>
<?php 
function after ($inthis, $inthat)
{
if (!is_bool(strpos($inthat, $inthis)))
return substr($inthat, strpos($inthat,$inthis)+strlen($inthis));
}
?>