<?php
defined('BASEPATH') OR exit('No direct script access allowed');
?>
<div class="container-fluid">	
	<div class="page_heading">
		<div class="row">
			<div class="col-sm-6">				
				<h1 style="float: left;"><?php echo $page_heading; ?></h1> <?php echo $this->breadcrumbs->show(); ?>	
			</div>
			<div class="col-sm-6">
				<div class="float-right">
					
					<a href="<?php echo site_url('challan'); ?>?order_id=<?php echo $ordersInfo->order_id; ?>" class="btn btn-primary" data-toggle="tooltip" data-placement="top" title="Create Challan"><i class="fas fa-plus"></i></a> &nbsp;
					
					<a href="<?php echo site_url('orderPrint'); ?>/<?php echo $ordersInfo->order_id; ?>" class="btn btn-primary" data-toggle="tooltip" data-placement="top" target="_blank" title="Print order"><i class="fas fa-print"></i></a> &nbsp;
					
					<a href="#" class="btn btn-primary" id="mailbox" data-toggle="tooltip" data-placement="top" title="Email"><i class="fas fa-envelope"></i></a> &nbsp;

					<a href="<?php echo site_url('order/downloadPdf'); ?>?order_id=<?php echo $ordersInfo->order_id; ?>" class="btn btn-primary" data-toggle="tooltip" data-placement="top" title="Download"> <i class="fas fa-download"></i></a> &nbsp;
					
					<a href="<?php echo site_url('ordChallan'); ?>/<?php echo $ordersInfo->order_id; ?>" class="btn btn-primary" data-toggle="tooltip" data-placement="top" title="Challan List"><i class="fa fa-list"></i></a>
				</div>
			</div>			
		</div>
	</div>
	
	<?php if(isset($success)){ ?>
		<div class="alert alert-success">
		  <?php echo $success; ?>
		</div>
	<?php } ?>
	
	<style>
		.quote_view p{margin-bottom:0px;}
		
		.borderbox{border:2px solid black;}
		.quote_view .border_left{border-left:2px solid black;}
		.quote_view .border_right{border-right:2px solid black;}
		.quote_view .border_bottom{border-bottom:2px solid black;}
		.quote_view .border_top{border-top:2px solid black;}
		
		table {
			table-layout:fixed;
		}
		
		.table-bordered td{
			border: 0px solid black;			
		}
		
		.space_bottom{margin-bottom:15px;}
		.card {border:0px solid rgba(0,0,0,.125);}
	</style>
	
	<div class="card mb-3">	
		<div class="card-body">
			<div class="row quote_view borderbox">
				<div class="col-sm-6 border_right">
					<p><b>Exporter:</b></p>
					<p><b>TARUN ENTERPRISES</b></p>
					<p><?php echo $ordersInfo->store_address; ?></p>
					<p>Phone: <?php echo $ordersInfo->store_phone; ?></p>
					<p>Email: <?php echo $ordersInfo->store_email; ?></p>
					<p>GST No: <?php echo $ordersInfo->store_gst_no; ?></p>
					<?php if($ordersInfo->store_name == 'Allahabad'){  ?>
						<p>Drug Licence: <?php echo $ordersInfo->drug_licence_no; ?></p>
						<p>Dt. <?php echo $ordersInfo->drug_date; ?></p>
					<?php } else { ?>
						<p>&nbsp;</p>						
					<?php } ?>
				</div>
				<div class="col-sm-6">
					<div class="row">
						<div class="col-sm-6 border_right border_bottom">
							<p><b>Order No:</b></p>
							<p style="margin-bottom: 15px;"><?php echo getOrderNo($ordersInfo->order_id); ?></p>
						</div>
						<div class="col-sm-6 border_bottom">
							<p><b>Order Date:</b></p>
							<p style="margin-bottom: 15px;"><?php echo dateFormat('F, d, Y', $ordersInfo->order_date); ?></p>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-6 border_right border_bottom">
							<p><b>Issued From:</b></p>
							<p style="margin-bottom: 15px;"><?php echo $ordersInfo->store_name; ?></p>
							
						</div>
						<div class="col-sm-6 border_bottom">
							<p><b>Currency:</b></p>
							<p style="margin-bottom: 15px;"><?php echo $ordersInfo->currency; ?></p>
							
						</div>
					</div>
					<div class="row">
						<div class="col-sm-6 border_right ">
							<p><b>Insurance:</b></p>
							<p style="margin-bottom: 15px;"><?php echo $ordersInfo->insurance; ?></p>
						</div>
						<div class="col-sm-6 ">
							<p><b>Generated by:</b></p>
							<p style="margin-bottom: 15px;"><?php echo $ordersInfo->firstname .' '.$ordersInfo->lastname; ?></p>
						</div>
					</div>
				</div>
				
				<div class="col-sm-6 border_top border_right addressformate">
					<p><b>Customer(Bill to):</b></p>
					<?php $billingAddress=nl2br($ordersInfo->billing_details);
						while(preg_match("/(.*?)\n/is",$billingAddress,$matcher)){
							print "<b>$matcher[1]</b>";
							$billingAddress=after($matcher[0],$billingAddress);
							break;
						}
					?>
					<?php echo $billingAddress; ?>					
					
					<?php if($customerInfo->gst){ ?>
					<p>GST No.: <?php echo $customerInfo->gst; ?></p>
					<?php } ?>
					<?php if($customerInfo->company_registration_no){ ?>
					<p>Reg. No.: <?php echo $customerInfo->company_registration_no; ?></p>
					<?php } ?>
					<?php if($customerInfo->drug_licence_no){ ?>
					<p>Drug Licence no.: <?php echo $customerInfo->drug_licence_no; ?></p>
					<?php } ?>	
				</div>
				
				<div class="col-sm-6 border_top">
					<p><b>Consingee(Ship to):</b></p>					
					<?php $shippingAddress=nl2br($ordersInfo->shipping_details);
						while(preg_match("/(.*?)\n/is",$shippingAddress,$matcher)){
							print "<b>$matcher[1]</b>";
							$shippingAddress=after($matcher[0],$shippingAddress);
							break;
						}
					?>
					<?php echo $shippingAddress; ?>
					
					<?php if($customerInfo->gst){ ?>
					<p>GST No.: <?php echo $customerInfo->gst; ?></p>
					<?php } ?>
					<?php if($customerInfo->company_registration_no){ ?>
					<p>Reg. No.: <?php echo $customerInfo->company_registration_no; ?></p>
					<?php } ?>
					<?php if($customerInfo->drug_licence_no){ ?>
					<p>Drug Licence no.: <?php echo $customerInfo->drug_licence_no; ?></p>
					<?php } ?>	
				</div>
				
				
				<div class="col-sm-6 border_top border_right border_bottom">
					<p><b>Terms of Delivery:</b></p>
					<p style="margin-bottom: 15px;"><?php echo $ordersInfo->delivery; ?></p>
				</div>
				<div class="col-sm-6 border_top border_bottom">
					<p><b>Terms of Payments:</b></p>
					<p style="margin-bottom: 15px;"><?php echo $ordersInfo->payment_terms; ?></p>
				</div>					
				
				<div class="col-sm-12 border_bottom">
					<p><b>Terms & Conditions:</b></p>
					<p style="margin-bottom: 15px;"><?php echo $ordersInfo->terms_conditions; ?></p>
				</div>
				
				<div class="col-sm-12 border_bottom">
					<p><b>Special Instruction:</b></p>
					<p style="margin-bottom: 15px;"><?php echo $ordersInfo->special_instruction; ?></p>
				</div>
				
				<table class="table-sm table-bordered" id="protable" width="100%" cellspacing="0">
					<tr>
						<th class="border_right" style="width:4%;">S.N.</th>
						<th  class="border_right" style="width:45.3%;">Product Description</th>
						<th class="border_right" style="width:10.5%; text-align:center;">HSN<?php if(($ordersInfo->currency == 'INR') && ($customerInfo->country_id == '99')){ echo '-GST'; ?><?php } ?></th>
						<th class="border_right" style="width:6%;text-align:center;">Qty</th>
						<th class="border_right" style="width:6%;text-align:center;">Unit</th>
						<th class="border_right" style="width:6%;text-align:center;">Rate</th>
						<th class="border_right" style="width:12%;text-align:center;">Discount/Unit</th>
						<th style="width:9%;text-align:right;" >Net Amount</th>
					</tr>
					
					<?php
						$net_total = 0;
						$i=1;
						foreach($orderProducts as $orderProduct){ 
							$net_total = $net_total + $orderProduct['net_amount'];					
					?>						
						<tr class="prtr" data-val="<?php echo $orderProduct['prod_id'];?>">
							<td class="border_right border_top"><?php echo $i; ?></td>
							<td class="border_right border_top"><b> <?php echo $orderProduct['model_name']; ?> </b> | <?php echo $orderProduct['description']; ?></td>
							<td align="center" class="border_right border_top"><?php echo $orderProduct['hsn']; ?><?php if(($ordersInfo->currency == 'INR') && ($customerInfo->country_id == '99')){ echo '<br>'.$orderProduct['product_gst']; ?> %<?php } ?></td>
							<td align="center" class="border_right border_top"><?php echo $orderProduct['qty']; ?></td>
							<td align="center" class="border_right border_top"><?php echo $orderProduct['unit']; ?></td>
							<td align="center" class="border_right border_top"><?php echo number_format((float)$orderProduct['rate'], 4, '.', ''); ?></td>
							<td align="center" class="border_right border_top"><?php echo number_format((float)$orderProduct['discount'], 4, '.', ''); ?></td>
							<td class="border_top" align="right"><?php echo number_format((float)$orderProduct['net_amount'], 2, '.', ''); ?></td>
						</tr>
					
					<?php $i++; } ?>					
					<tr class="nettottr">
						<td class="border_right border_top" colspan="7" align="right" ><b>Net Total</b></td>
						<td class="border_right border_top" align="right"> <i class="<?php echo $ordersInfo->currency_faclass; ?>" style="font-size:13px;"></i>&nbsp; <span id="net_total"><?php echo number_format((float)$net_total, 2, '.', ''); ?></span></td>
					</tr>
					<tr class="ftr">
						<td class="border_right border_top" colspan="7" align="right" ><b>Freight Charges</b></td>
						<td class="border_right border_top" align="right"> <i class="<?php echo $ordersInfo->currency_faclass; ?>" style="font-size:13px;"></i>&nbsp; 
						<span id="freight_charge"><?php echo number_format((float)$ordersInfo->freight_charge, 2, '.', ''); ?></span></td>
					</tr>
							<?php
								if(($ordersInfo->currency == 'INR') && ($customerInfo->countryId == '99')){
									if($productgst){ 
										$totwithgst = 0;
										$freight_charge = $ordersInfo->freight_charge;
										$freight_gst = $ordersInfo->freight_gst;
										$flagFreightGST=1;# set 0 if GST% of freight charge is in the list of products.
										#i.e to cheate the row for GST @ 18% (Freight GST)
										foreach($productgst as $progst){
											$perProFrchWthGst=0;
											if($freight_gst==0){
												$perProFrch = ($freight_charge / $net_total) * $progst['net_amount'];
												$perProFrchWthGst = ($perProFrch * $progst['product_gst']/100);
											}else if(!empty($freight_gst)){
												if($freight_gst==$progst['product_gst']){
													$perProFrchWthGst = ($freight_charge * $freight_gst)/100;
													$flagFreightGST=0;
												}
											}

											$totgst = $perProFrchWthGst + ($progst['net_amount'] * $progst['product_gst']/100);	
											$totgst = number_format((float)$totgst, 2, '.', '');
											$totwithgst = $totwithgst + $totgst;
											?>
										
											<tr>
												<td class="border_right border_top" colspan="7" align="right" ><b>GST @ <?php echo $progst['product_gst']; ?>%</b></td>
												<td class="border_right border_top" align="right"> <i class="<?php echo $ordersInfo->currency_faclass; ?>" style="font-size:13px;"></i>&nbsp; <?php echo number_format((float)$totgst, 2, '.', ''); ?></td>
											</tr>
									<?php } ?>
										<?php if($flagFreightGST==1 && $freight_gst>0){ 
											$perProFrchWthGst = ($freight_charge * $freight_gst)/100;
											$totgst = $perProFrchWthGst;
											$totgst = number_format((float)$totgst, 2, '.', '');
											$totwithgst = $totwithgst + $totgst;
										?>
											<tr>
												<td class="border_right border_top" colspan="7" align="right" ><b>GST @ <?php echo $freight_gst; ?>%</b></td>
												<td class="border_right border_top" align="right"> <i class="<?php echo $ordersInfo->currency_faclass; ?>" style="font-size:13px;"></i>&nbsp; <?php echo number_format((float)$totgst, 2, '.', ''); ?></td>
											</tr>
										<?php } ?>
								<?php } ?>
						<?php } ?>
					<tr class="grndtr">
						<td class="border_right border_top" colspan="7" align="right" ><b>Grand Total</b></td>
						<td class="border_right border_top" align="right"> <b><i class="<?php echo $ordersInfo->currency_faclass; ?>" style="font-size:13px;"></i>&nbsp; <span id="grand_total"><?php echo number_format((float)($net_total + $ordersInfo->freight_charge + $totwithgst), 2, '.', ''); ?></span></b></td>
					</tr>
				</table>
			</div>
			<br>
			<div class="row">
					<div class="col-sm-12" style="padding-right: 0px;padding-left: 0px;">
						<p style="margin: 0px;">Greetings!<br>
Thank you for your valued order. Same is under process. We request you to please check all the details as above and arrange payment as per banking details below. In case you wish to use online payment , please use our payment gateway at our website <a href="http://www.optitecheyecare.com/payment.php">www.optitecheyecare.com</a> .</p> 
						<p style="margin: 0px;"></p>						
					</div>					
				</div>
				<br>
				<div class="row">
					<div class="col-sm-12" style="padding-right: 0px;padding-left: 0px;">
						<p style="margin: 0px;">Remit to:</p>
					</div>
					
					<div class="col-sm-6" style="padding-right: 0px;padding-left: 0px;">					
						<div style="width:100%;float:left;">
							<p style="margin: 0px;width:40%;float:left;"><b>Payment :</b></p><p style="margin: 0px;float:left;">100% T/T(wire)</p>
						</div>	
						<div style="width:100%;float:left;">
							<p style="margin: 0px;width:40%;float:left;"><b>Beneficiary's Name:</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->beneficiary_name; ?></p>
						</div>
						
						<div style="width:100%;float:left;">
							<p style="margin: 0px;width:40%;float:left;"><b>Bank Name:</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->bank_name; ?></p>
						</div>
						
					</div>
					
					<div class="col-sm-6" style="padding-right: 0px;padding-left: 0px;">					
						<div style="width:100%;float:left;">
							<p style="margin: 0px;width:40%;float:left;"><b>Bank Details for</b></p><p style="margin: 0px;float:left;"> (<?php echo $ordersInfo->currency; ?>)</p>
						</div>	
						<div style="width:100%;float:left;">	
							<p style="margin: 0px;width:40%;float:left;"><b>Account No.:</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->account_number; ?></p>
						</div>
						
						<?php if($ordersInfo->currency == 'INR'){ ?>
							<?php if(!empty($bankInfo->ifsc_code)){ ?>
								<div style="width:100%;float:left;">
									<p style="margin: 0px;width:40%;float:left;"><b>IFSC Code :</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->ifsc_code; ?></p>
								</div>
							<?php } ?>
						<?php } else { ?>						
							<?php if(!empty($bankInfo->swift_code)){ ?>
								<div style="width:100%;float:left;">
									<p style="margin: 0px;width:40%;float:left;"><b>SWIFT Code :</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->swift_code; ?></p>
								</div>
							<?php } ?>	
						<?php } ?>						
					</div>
					
					<div class="col-sm-12" style="padding-right: 0px;padding-left: 0px;">					
						<div style="width:100%;float:left;">
							<p style="margin: 0px;width:20%;float:left;"><b>Bank Address :</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->bank_address; ?></p>
						</div>										
					</div>				
				
					<div class="col-sm-12" style="padding-right: 0px;padding-left: 0px;">						
						<p style="margin: 0px;">Bank remittance charge shall be paid by payer(buyer)</p><br>
						<p style="margin: 0px;">For Tarun Enterprises</p><br><br>
						<p style="margin: 0px;">Order Processing Team</p><br>
						<p style="margin: 0px;font-size:14px;">Created by (<?php echo $ordersInfo->firstname .' '.$ordersInfo->lastname; ?>)</p> 
					</div>					
				</div>
		</div>		
	</div>	
</div>

<div class="modal fade" id="myModal" role="dialog">
	<div class="modal-dialog" >				
	  <!-- Modal content-->
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">Send Mail</h4>
				<button type="button" class="close" data-dismiss="modal">&times;</button>			  
			</div>
			<div id="alert-danger"></div>
			<div class="modal-body">
				<form method="post" action="" id="orderMailForm" enctype="multipart/form-data" >					
					<div class="form-group">
						<div class="row">						
							<div class="col-sm-2">To :</div>															
							<div class="col-sm-10"> <input type="text" name="email_to" value="<?php echo $ordersInfo->contact_email; ?>" autocomplete='off'  id="email_to" class="form-control" required></div>
						</div>						
					</div>
					
					<div class="form-group">
						<div class="row">						
							<div class="col-sm-2">CC :</div>															
							<div class="col-sm-10"> <input type="text" name="email_cc" value=""  id="email_cc" autocomplete='off' class="form-control"></div>
						</div>						
					</div>
					
					<div class="form-group">
						<div class="row">						
							<div class="col-sm-2">Subject:</div>															
							<div class="col-sm-10"> <input type="text" name="email_subject" autocomplete='off' value="Order / Performa Invoice - <?php echo getOrderNo($ordersInfo->order_id); ?>"  id="email_subject" class="form-control" required></div>
						</div>						
					</div>
					
					<div class="form-group">
						<div class="row">						
							<div class="col-sm-2">Massage:</div>															
							<div class="col-sm-10">
							<textarea class="form-control" rows="7" name="email_massage" id="email_massage">Dear <?php echo $customerInfo->person_title; ?> <?php echo $ordersInfo->contact_person; ?>,

Please find the Order as attached in email bellow.

Thank you,
Optitech Eye Care</textarea>
							</div>
						</div>						
					</div>
					
					<div id="orderfiletextbox"> </div>
					
					<div class="form-group">
						<div class="row">						
							<div class="col-sm-2">File:</div>															
							<div class="col-sm-10">
								<div id="orderfile"></div>
							</div>
						</div>						
					</div>
					
					<div class="row">
						<div class="col-sm-12">
							<div class="form-group">									
								<button type="button" id="sendMail" class="btn btn-primary float-right"> Send Mail</button>	
							</div>
						</div>						
					</div>					
				</form>
			</div>
		</div>				  
	</div>
</div>

<script>
	$(document).ready(function(){	
		$("#mailbox").click(function(){			
			$.ajax({
				url:'<?php echo site_url('order/orderSavePdf'); ?>',
				method: 'post',
				data: 'order_id=<?php echo $ordersInfo->order_id; ?>', 
				dataType: 'json',
				beforeSend: function(){
					$('.loader').show();
				},
				complete: function(){
					$('.loader').hide();
				},
				success: function(response){
				    if(response){						
						var htm = '';
						var hiddentext = '';						
						$.each(response, function(i,res) {
							
							htm += '<a href="<?php echo base_url(); ?>'+ res.order_file +'" target="_blank" > '+ res.order_file_name +' </a> &nbsp;';
							
							hiddentext += '<input type="hidden" name="order_file" value="'+res.order_file+'">';							
						});						
						$("#orderfile").html(htm);
						
						$("#orderfiletextbox").html(hiddentext); 
					}
					$("#myModal").modal();		
				}
			});				
		});
		
		$("#sendMail").click(function(){		
			var data_form = $('#orderMailForm').serialize();
			$.ajax({
				url:'<?php echo site_url('orderSendMail'); ?>',
				method: 'post',
				data: data_form,
				dataType: 'json',
				success: function(response){
					$("#alert-danger").html('');
					var htm = '<div class="alert alert-success" role="alert">Successfully Mail Send.</div>';
					$("#alert-danger").html(htm);
					setTimeout(function(){
						$("#myModal .close").click();
						$("#alert-danger").html('');
					}, 3000);
				}
			});				
		});		
	});
</script>
<?php 
function after ($inthis, $inthat)
{
if (!is_bool(strpos($inthat, $inthis)))
return substr($inthat, strpos($inthat,$inthis)+strlen($inthis));
}
?>