<?php
defined('BASEPATH') OR exit('No direct script access allowed');
?>
<div class="container-fluid">	
	<div class="page_heading">
		<div class="row">
			<div class="col-sm-6">				
				<h1 style="float: left;"><a href="<?php echo site_url('orderView'); ?>/<?php echo $ordersInfo->order_id; ?>"><?php echo getOrderNo($ordersInfo->order_id); ?></a> | <?php echo $ordersInfo->customer_name; ?> | <?php echo date('F, d, Y', strtotime($ordersInfo->order_date)); ?></h1> <?php echo $this->breadcrumbs->show(); ?>
			</div>
			<!-- <div class="col-sm-6">
				<div class="float-right">
					
					<a href="<?php echo site_url('challan'); ?>?order_id=<?php echo $ordersInfo->order_id; ?>" class="btn btn-primary" data-toggle="tooltip" data-placement="top" title="Create Challan"><i class="fas fa-plus"></i></a> &nbsp;
					
					<a href="<?php echo site_url('orderPrint'); ?>/<?php echo $ordersInfo->order_id; ?>" class="btn btn-primary" data-toggle="tooltip" data-placement="top" target="_blank" title="Print order"><i class="fas fa-print"></i></a> &nbsp;
					
					<a href="#" class="btn btn-primary" id="mailbox" data-toggle="tooltip" data-placement="top" title="Email"><i class="fas fa-envelope"></i></a> &nbsp;

					<a href="<?php echo site_url('order/downloadPdf'); ?>?order_id=<?php echo $ordersInfo->order_id; ?>" class="btn btn-primary" data-toggle="tooltip" data-placement="top" title="Download"> <i class="fas fa-download"></i></a> &nbsp;
					
					<a href="<?php echo site_url('ordChallan'); ?>/<?php echo $ordersInfo->order_id; ?>" class="btn btn-primary" data-toggle="tooltip" data-placement="top" title="Challan List"><i class="fa fa-list"></i></a>
				</div>
			</div> -->			
		</div>
	</div>
	
	<?php if(isset($success)){ ?>
		<div class="alert alert-success">
		  <?php echo $success; ?>
		</div>
	<?php } ?>
	
	<style>
		.quote_view p{margin-bottom:0px;}
		
		.borderbox{border:2px solid black;}
		.quote_view .border_left{border-left:2px solid black;}
		.quote_view .border_right{border-right:2px solid black;}
		.quote_view .border_bottom{border-bottom:2px solid black;}
		.quote_view .border_top{border-top:2px solid black;}
		
		table {
			table-layout:fixed;
		}
		
		.table-bordered td{
			border: 0px solid black;			
		}
		
		.space_bottom{margin-bottom:15px;}
		.card {border:0px solid rgba(0,0,0,.125);}
	</style>
	
	<div class="card mb-3">	
		<div class="card-body">
			<div class="row quote_view borderbox">
				<!-- <div class="col-sm-6 border_right">
					<p><b>Exporter:</b></p>
					<p><b>TARUN ENTERPRISES</b></p>
					<p><?php echo $ordersInfo->store_address; ?></p>
					<p>Phone: <?php echo $ordersInfo->store_phone; ?></p>
					<p>Email: <?php echo $ordersInfo->store_email; ?></p>
					<p>GST No: <?php echo $ordersInfo->store_gst_no; ?></p>
					<?php if($ordersInfo->store_name == 'Allahabad'){  ?>
						<p>Drug Licence: ALLD/5/21B/385,ALLD/5/20B/388</p>
						<p>Dt. 06.05.2008</p>
					<?php } else { ?>
						<p>&nbsp;</p>						
					<?php } ?>
				</div>
				<div class="col-sm-6">
					<div class="row">
						<div class="col-sm-6 border_right border_bottom">
							<p><b>Order No:</b></p>
							<p style="margin-bottom: 15px;"><?php echo getOrderNo($ordersInfo->order_id); ?></p>
						</div>
						<div class="col-sm-6 border_bottom">
							<p><b>Order Date:</b></p>
							<p style="margin-bottom: 15px;"><?php echo date('F, d, Y', strtotime($ordersInfo->order_date)); ?></p>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-6 border_right border_bottom">
							<p><b>Issued From:</b></p>
							<p style="margin-bottom: 15px;"><?php echo $ordersInfo->store_name; ?></p>
							
						</div>
						<div class="col-sm-6 border_bottom">
							<p><b>Currency:</b></p>
							<p style="margin-bottom: 15px;"><?php echo $ordersInfo->currency; ?></p>
							
						</div>
					</div>
					<div class="row">
						<div class="col-sm-6 border_right ">
							<p><b>Insurance:</b></p>
							<p style="margin-bottom: 15px;"><?php echo $ordersInfo->insurance; ?></p>
						</div>
						<div class="col-sm-6 ">
							<p><b>Generated by:</b></p>
							<p style="margin-bottom: 15px;"><?php echo $ordersInfo->firstname .' '.$ordersInfo->lastname; ?></p>
						</div>
					</div>
				</div> -->
				
				<!-- <div class="col-sm-6 border_top border_right addressformate">
					<p><b>Customer(Bill to):</b></p>
					<?php $billingAddress=nl2br($ordersInfo->billing_details);
						while(preg_match("/(.*?)\n/is",$billingAddress,$matcher)){
							print "<b>$matcher[1]</b>";
							$billingAddress=after($matcher[0],$billingAddress);
							break;
						}
					?>
					<?php echo $billingAddress; ?>					
					
					<?php if($customerInfo->gst){ ?>
					<p>GST No.: <?php echo $customerInfo->gst; ?></p>
					<?php } ?>
					<?php if($customerInfo->company_registration_no){ ?>
					<p>Reg. No.: <?php echo $customerInfo->company_registration_no; ?></p>
					<?php } ?>			
				</div>
				
				<div class="col-sm-6 border_top">
					<p><b>Consingee(Ship to):</b></p>					
					<?php $shippingAddress=nl2br($ordersInfo->shipping_details);
						while(preg_match("/(.*?)\n/is",$shippingAddress,$matcher)){
							print "<b>$matcher[1]</b>";
							$shippingAddress=after($matcher[0],$shippingAddress);
							break;
						}
					?>
					<?php echo $shippingAddress; ?>
					
					<?php if($customerInfo->gst){ ?>
					<p>GST No.: <?php echo $customerInfo->gst; ?></p>
					<?php } ?>
					<?php if($customerInfo->company_registration_no){ ?>
					<p>Reg. No.: <?php echo $customerInfo->company_registration_no; ?></p>
					<?php } ?>	
				</div> -->
				
				
				<div class="col-sm-6 border_top border_right border_bottom">
					<p><b>Terms of Delivery:</b></p>
					<p style="margin-bottom: 15px;"><?php echo $ordersInfo->delivery; ?></p>
				</div>
				<div class="col-sm-6 border_top border_bottom">
					<p><b>Terms of Payments:</b></p>
					<p style="margin-bottom: 15px;"><?php echo $ordersInfo->payment_terms; ?></p>
				</div>

				<div class="col-sm-12 border_bottom">
					<p><b>Terms & Conditions:</b></p>
					<p style="margin-bottom: 15px;"><?php echo $ordersInfo->terms_conditions; ?></p>
				</div>
				
				<div class="col-sm-12 border_bottom">
					<p><b>Special Instruction</b></p>
					<p style="margin-bottom: 15px;"><?php echo $ordersInfo->special_instruction; ?></p>
				</div>
				
				<table class="table-sm table-bordered" id="protable" width="100%" cellspacing="0">
					<tr>
						<th class="border_right" style="width:4%;">S.N.</th>
						<th  class="border_right" style="width:45.3%;">Product Description</th>
						<th class="border_right" style="width:10.5%; text-align:center;">HSN</th>
						<th class="border_right" style="width:6%;text-align:center;">Unit</th>
						<th class="border_right" style="width:6%;text-align:center;">OrderQty</th>
						<th class="border_right" style="width:6%;text-align:center;">PendingQty</th>
						
						<!-- <th class="border_right" style="width:6%;text-align:center;">Rate</th>
						<th class="border_right" style="width:12%;text-align:center;">Disc(Per Unit)</th>
						<th style="width:9%;text-align:right;" >Net Amount</th> -->
					</tr>
					
					<?php
						$net_total = 0;
						$i=1;
						foreach($orderProducts as $orderProduct){ 
							$net_total = $net_total + $orderProduct['net_amount'];					
					?>						
						<tr class="prtr" data-val="<?php echo $orderProduct['prod_id'];?>">
							<td class="border_right border_top"><?php echo $i; ?></td>
							<td class="border_right border_top"><b> <?php echo $orderProduct['model_name']; ?> </b> | <?php echo $orderProduct['description']; ?></td>
							<td align="center" class="border_right border_top"><?php echo $orderProduct['hsn']; ?></td>
							<td align="center" class="border_right border_top"><?php echo $orderProduct['unit']; ?></td>
							<td align="center" class="border_right border_top"><?php echo $orderProduct['qty']; ?></td>
							<td align="center" class="border_right border_top"><?php echo $orderProduct['qty'] - $orderProduct['challan_qty']; ?></td>
							
							<!-- <td align="center" class="border_right border_top"><?php echo number_format((float)$orderProduct['rate'], 4, '.', ''); ?></td>
							<td align="center" class="border_right border_top"><?php echo number_format((float)$orderProduct['discount'], 4, '.', ''); ?></td>
							<td class="border_top" align="right"><?php echo number_format((float)$orderProduct['net_amount'], 2, '.', ''); ?></td> -->
						</tr>
					
					<?php $i++; } ?>					
					<!-- <tr class="nettottr">
						<td class="border_right border_top" colspan="7" align="right" ><b>Net Total</b></td>
						<td class="border_right border_top" align="right"> <i class="<?php echo $ordersInfo->currency_faclass; ?>" style="font-size:13px;"></i>&nbsp; <span id="net_total"><?php echo number_format((float)$net_total, 2, '.', ''); ?></span></td>
					</tr>
					<tr class="ftr">
						<td class="border_right border_top" colspan="7" align="right" ><b>Freight Charges</b></td>
						<td class="border_right border_top" align="right"> <i class="<?php echo $ordersInfo->currency_faclass; ?>" style="font-size:13px;"></i>&nbsp; 
						<span id="freight_charge"><?php echo number_format((float)$ordersInfo->freight_charge, 2, '.', ''); ?></span></td>
					</tr>
							<?php
								if($ordersInfo->currency == 'INR'){
								if($productgst){ 
								$totwithgst = 0;
								$freight_charge = $ordersInfo->freight_charge;
								foreach($productgst as $progst){
								$perProFrch = ($freight_charge / $net_total) * $progst['net_amount'];
								$perProFrchWthGst = ($perProFrch * $progst['product_gst']/100);
								$totgst = $perProFrchWthGst + ($progst['net_amount'] * $progst['product_gst']/100);								
								$totwithgst = $totwithgst + $totgst;
							?>
						
							<tr>
								<td class="border_right border_top" colspan="7" align="right" ><b>GST @ <?php echo $progst['product_gst']; ?>%</b></td>
								<td class="border_right border_top" align="right"> <i class="<?php echo $ordersInfo->currency_faclass; ?>" style="font-size:13px;"></i>&nbsp; <?php echo number_format((float)$totgst, 2, '.', ''); ?></td>
							</tr>
						<?php } ?>
						<?php } ?>
						<?php } ?>
					<tr class="grndtr">
						<td class="border_right border_top" colspan="7" align="right" ><b>Grand Total</b></td>
						<td class="border_right border_top" align="right"> <b><i class="<?php echo $ordersInfo->currency_faclass; ?>" style="font-size:13px;"></i>&nbsp; <span id="grand_total"><?php echo number_format((float)($net_total + $ordersInfo->freight_charge + $totwithgst), 2, '.', ''); ?></span></b></td>
					</tr> -->
				</table>
			</div>
			<br>
			<!--  <div class="row">
					<div class="col-sm-12" style="padding-right: 0px;padding-left: 0px;">
						<p style="margin: 0px;">Greetings!<br>
Thank you for your valued order. Same is under process. We request you to please check all the details as above and arrange payment as per banking details below. In case you wish to use online payment , please use our payment gateway at our website <a href="www.optitecheyecare.com">www.optitecheyecare.com</a> .</p> 
						<p style="margin: 0px;"></p>						
					</div>					
				</div>
				<br>
				<div class="row">
					<div class="col-sm-12" style="padding-right: 0px;padding-left: 0px;">
						<p style="margin: 0px;">Remit to:</p> 
						<div style="width:100%;float:left;">
							<p style="margin: 0px;width:15%;float:left;"><b>Payment :</b></p><p style="margin: 0px;float:left;">100% T/T(wire)</p>
						</div>
						<div style="width:100%;float:left;">
							<p style="margin: 0px;width:15%;float:left;"><b>Bank Details for</b></p><p style="margin: 0px;float:left;"> (<?php echo $ordersInfo->currency; ?>)</p>
						</div>
						<div style="width:100%;float:left;">
							<p style="margin: 0px;width:15%;float:left;"><b>Beneficiary's Name:</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->beneficiary_name; ?></p>
						</div>
						<div style="width:100%;float:left;">	
							<p style="margin: 0px;width:15%;float:left;"><b>Account No.:</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->account_number; ?></p>
						</div>
						<div style="width:100%;float:left;">
							<p style="margin: 0px;width:15%;float:left;"><b>Bank Name:</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->bank_name; ?></p>
						</div>
						<div style="width:100%;float:left;">
							<p style="margin: 0px;width:15%;float:left;"><b>Bank Address:</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->bank_address; ?></p>
						</div>
						
						<?php if(!empty($bankInfo->swift_code)){ ?>
							<div style="width:100%;float:left;">
								<p style="margin: 0px;width:15%;float:left;"><b>SWIFT Code:</b></p><p style="margin: 0px;float:left;"><?php echo $bankInfo->swift_code; ?></p>
							</div>
						<?php } ?>
						<?php if(!empty($bankInfo->ifsc_code)){ ?>
							<div style="width:100%;float:left;">
								<p style="margin: 0px;width:15%;float:left;"><b>IFSC Code:</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->ifsc_code; ?></p>
							</div>
						<?php } ?>
						<p style="margin: 0px;">Bank remittance charge shall be paid by payer(buyer)</p><br>
						<p style="margin: 0px;">For Tarun Enterprises</p><br><br>
						<p style="margin: 0px;">Order Processing Team</p><br>
						<p style="margin: 0px;font-size:14px;">Created by (<?php echo $ordersInfo->firstname .' '.$ordersInfo->lastname; ?>)</p> 
					</div>					
				</div> -->
		</div>		
	</div>	
</div>
<?php 
function after ($inthis, $inthat)
{
if (!is_bool(strpos($inthat, $inthis)))
return substr($inthat, strpos($inthat,$inthis)+strlen($inthis));
}
?>