<?php
defined('BASEPATH') OR exit('No direct script access allowed');
?>
<div class="container-fluid">	
	<form action="<?php echo site_url('saveOrder'); ?>" method="POST" name="saveOrderForm" id="saveOrderForm">
	<input type="hidden" name="quotation_id" value="<?php echo $quotationInfo->quote_id; ?>">	
	<div class="page_heading">
		<div class="row">
			<div class="col-sm-6">				
				<h1 style="float: left;"><?php echo $page_heading; ?></h1> <?php echo $this->breadcrumbs->show(); ?>
			</div>
			<div class="col-sm-6">
				<div class="float-right">
					<!-- <button type="submit" class="btn btn-primary" data-toggle="tooltip" data-placement="top" title="Save Order"> <i class="fas fa-save"></i></button> -->				
					<button type="button" id="priviewOrder" class="btn btn-primary" data-toggle="tooltip" data-placement="top" title="Preview Order"> <!-- <i class="fas fa-save"></i> -->Preview Order</button>					
				</div>
			</div>
		</div>
	</div>
	
	<?php if(isset($success)){ ?>
		<div class="alert alert-success">
		  <?php echo $success; ?>
		</div>
	<?php } ?>
	
	<style>
		.quote_view p{margin-bottom:0px;}
		
		.borderbox{border:2px solid gray;}
		.quote_view .border_left{border-left:2px solid gray;}
		.quote_view .border_right{border-right:2px solid gray;}
		.quote_view .border_bottom{border-bottom:2px solid gray;}
		.quote_view .border_top{border-top:2px solid gray;}
		
		table {
			table-layout:fixed;
		}
		
		.table-bordered td{
			border: 0px solid gray;			
		}
		
		.space_bottom{margin-bottom:15px;}
		.card {border:0px solid rgba(0,0,0,.125);}
	</style>
	
	<div class="card mb-3">	
		<div class="card-body">
			<div class="row quote_view borderbox">
				<div class="col-sm-6 border_right">
					<p><b>Exporter:</b></p>
					<p><b>TARUN ENTERPRISES</b></p>
					<p><?php echo $quotationInfo->store_address; ?></p>
					<p>Phone: <?php echo $quotationInfo->store_phone; ?></p>
					<p>Email: <?php echo $quotationInfo->store_email; ?></p>
					<p>GST No: <?php echo $quotationInfo->store_gst_no; ?></p>
					<?php if($quotationInfo->store_name == 'Allahabad'){  ?>
						<p>Drug Licence: <?php echo $quotationInfo->drug_licence_no; ?></p>
						<p>Dt. <?php echo $quotationInfo->drug_date; ?></p>
					<?php } else { ?>
						<p>&nbsp;</p>						
					<?php } ?>
				</div>
				<div class="col-sm-6">
					<div class="row">
						<div class="col-sm-6 border_right border_bottom">
							<p><b>Quotation No:</b></p>
							<p style="margin-bottom: 15px;"><?php echo getQuotationNo($quotationInfo->quote_id); ?></p>
						</div>
						<div class="col-sm-6 border_bottom">
							<p><b>Quotation Date:</b></p>
							<p style="margin-bottom: 15px;"><?php echo dateFormat('F, d, Y', $quotationInfo->quotation_date); ?></p>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-6 border_right border_bottom">
							<p><b>Issued From:</b></p>
							<p style="margin-bottom: 15px;"><?php echo $quotationInfo->store_name; ?></p>
							
						</div>
						<div class="col-sm-6 border_bottom">
							<p><b>Currency:</b></p>
							<p style="margin-bottom: 15px;"><?php echo $quotationInfo->currency; ?></p>
							
						</div>
					</div>
					<div class="row">
						<div class="col-sm-6 border_right ">
							<p><b>Insurance:</b></p>
							<p style="margin-bottom: 15px;"><?php echo $quotationInfo->insurance; ?></p>
						</div>
						<div class="col-sm-6 ">
							<p><b>Generated by:</b></p>
							<p style="margin-bottom: 15px;"><?php echo $quotationInfo->firstname .' '.$quotationInfo->lastname; ?></p>
						</div>
					</div>
				</div>
				
				<div class="col-sm-6 border_top border_right">
					<p><b>Customer(Bill to):</b></p>
					<?php //echo nl2br($quotationInfo->billing_details); ?>
					<select name="billing_details_default" id="billing_details_default" class="form-control">
						<option value="">-- Select --</option>
						<?php $i=1; foreach($addresses as $address){ ?>							
							<option value="<?php echo $address['address_id']; ?>"> <?php $address['address_id'] = ''; ?> <?php echo implode(', ',array_filter($address)); ?></option>
						<?php $i++; } ?>
					</select>
					<textarea name="billing_details" id="billing_details" rows="8"  class="form-control" required><?php if($quotationInfo->billing_details) { echo $quotationInfo->billing_details; } ?></textarea>
				</div>
				
				<div class="col-sm-6 border_top">
					<p><b>Consingee(Ship to):</b> &nbsp;&nbsp; <input type="checkbox" name="same_address" id="same_address"><span style="color:gray;"> Same as Bill Details</span></p>					
					<?php //echo nl2br($quotationInfo->shipping_details); ?>
					<select name="shipping_details_default" id="shipping_details_default" class="form-control">	
						<option value="">-- Select --</option>
						<?php $i=1; foreach($addresses as $address){ ?>							
							<option value="<?php echo $address['address_id']; ?>"> <?php $address['address_id'] = ''; ?> <?php echo implode(', ',array_filter($address)); ?></option>
						<?php $i++; } ?>
					</select>
					<textarea name="shipping_details" id="shipping_details" rows="8" class="form-control" required><?php if($quotationInfo->shipping_details) { echo $quotationInfo->shipping_details; } ?></textarea>
				</div>
				
				<div class="col-sm-6 border_top border_right border_bottom">
					<div class="row">
						<div class="col-sm-6 border_right">
							<p><b>Terms of Delivery:</b></p>
							<p style="margin-bottom: 15px;"><?php echo $quotationInfo->delivery; ?></p>
						</div>
						<div class="col-sm-6">
							<p><b>Terms of Payments:</b></p>
							<p style="margin-bottom: 15px;"><?php echo $quotationInfo->payment_terms; ?></p>
						</div>
					</div>
				</div>
				
				<div class="col-sm-6 border_top border_bottom">
					<p><b>Terms & Conditions:</b></p>
					<p style="margin-bottom: 15px;"><?php echo $quotationInfo->terms_conditions; ?></p>
				</div>
				
				<table class="table-sm table-bordered" id="protable" width="100%" cellspacing="0">
					<tr>
						<th class="border_right" style="width:4%;">S.N.</th>
						<th class="border_right" style="width:45.3%;">Product Description</th>
						<th class="border_right" style="width:10.5%;">HSN</th>
						<th class="border_right" style="width:6%;">Qty</th>
						<th class="border_right" style="width:6%;">Unit</th>
						<th class="border_right" style="width:6%;">Rate</th>
						<th class="border_right" style="width:12%;">Discount/Unit</th>
						<th style="width:9%;" align="right">Net Amount</th>
					</tr>
					
					<?php
						$net_total = 0;
						$i=1;
						foreach($quoteProductInfo as $productInfo){ 
							$net_total = $net_total + $productInfo['net_amount'];
							$gstAmount=(((float)$productInfo['rate']-(float)$productInfo['discount'])*$productInfo['product_gst'])/100;
							$gstAmount=$gstAmount*$productInfo['qty'];
					?>						
						<tr class="prtr" data-val="<?php echo $productInfo['prod_id'];?>">
							<input type="hidden" name="gst[<?php echo $productInfo['product_gst'];?>]" id="gst_<?php echo $productInfo['prod_id'];?>" value="<?php echo $productInfo['product_gst'];?>">
							<input type="hidden" name="gstAmount[<?php echo $productInfo['product_gst'];?>]" id="gstAmt_<?php echo $productInfo['prod_id'];?>" value="<?php echo number_format((float)$gstAmount, 2, '.', ''); ?>">
							<td class="border_right border_top"><input type="checkbox" name="product_id[]" class="procheckbox" id="pro_<?php echo $productInfo['prod_id'];?>" value="<?php echo $productInfo['prod_id'];?>" checked>&nbsp;&nbsp;<?php echo $i; ?></td>
							<td class="border_right border_top"><b><?php echo $productInfo['model_name']; ?></b> | <?php echo $productInfo['description']; ?></td>
							<td class="border_right border_top"><?php echo $productInfo['hsn']; ?></td>
							<td class="border_right border_top"><input type="text" name="qty[<?php echo $productInfo['prod_id'];?>]" class="qty" id="proqty_<?php echo $productInfo['prod_id'];?>" style="width:57px;border: 1px solid gray;" value="<?php echo $productInfo['qty']; ?>"></td>
							<td class="border_right border_top"><?php echo $productInfo['unit']; ?></td>
							<td class="border_right border_top"><?php echo number_format((float)$productInfo['rate'], 4, '.', ''); ?></td>
							<td class="border_right border_top"><?php echo number_format((float)$productInfo['discount'], 4, '.', ''); ?></td>
							
							<input type="hidden" name="pro_amount[<?php echo $productInfo['prod_id'];?>]" id="proamt_<?php echo $productInfo['prod_id'];?>" value="<?php echo number_format((float)$productInfo['net_amount'], 2, '.', ''); ?>">
							<td class="border_top" align="right"><?php echo number_format((float)$productInfo['net_amount'], 2, '.', ''); ?></td>
						</tr>
					
					<?php $i++; } ?>					
					<tr class="nettottr">
						<td class="border_right border_top" colspan="7" align="right" >Net Total</td>
						<td class="border_right border_top" align="right"> <i class="<?php echo $quotationInfo->currency_faclass; ?>" style="font-size:13px;"></i>&nbsp; <span id="net_total"><?php echo number_format((float)$net_total, 2, '.', ''); ?></span></td>
					</tr>
					<tr class="ftr">
						<td class="border_right border_top" colspan="7" align="right" ><span style="float:left;"><b>Please enter Freight Charges : </b><input type="text" name="freightcharge" autocomplete="off" id="freightcharge" style="width:100px;border: 1px solid gray;" value="<?php echo number_format((float)$quotationInfo->freight_charge, 2, '.', ''); ?>"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Freight Charges</td>
						<td class="border_right border_top" align="right"> <i class="<?php echo $quotationInfo->currency_faclass; ?>" style="font-size:13px;"></i>&nbsp; 
						<span id="freight_charge"><?php echo number_format((float)$quotationInfo->freight_charge, 2, '.', ''); ?></span></td>
					</tr>
				
					<tbody id="progstall">
							<?php
								if(($quotationInfo->currency == 'INR') && ($customerInfo->countryId == '99')){
								if($productgst){ 
								$totwithgst = 0;
								$freight_charge = $quotationInfo->freight_charge;
								$freight_gst = $this->config->item('PER_FREIGHT_GST');
								$flagFreightGST=1;# set 0 if GST% of freight charge is in the list of products.
									#i.e to cheate the row for GST @ 18% (Freight GST)
								foreach($productgst as $progst){
								/* $perProFrch = ($freight_charge / $net_total) * $progst['net_amount'];
								$perProFrchWthGst = ($perProFrch * $progst['product_gst']/100);
								$totgst = $perProFrchWthGst + ($progst['net_amount'] * $progst['product_gst']/100);								
								$totwithgst = $totwithgst + $totgst; */
								$perProFrchWthGst=0;
								if($freight_gst==0){
									$perProFrch = ($freight_charge / $net_total) * $progst['net_amount'];
									$perProFrchWthGst = ($perProFrch * $progst['product_gst']/100);
								}else if(!empty($freight_gst)){
									if($freight_gst==$progst['product_gst']){
										$perProFrchWthGst = ($freight_charge * $freight_gst)/100;
										$flagFreightGST=0;
									}
								}

								$totgst = $perProFrchWthGst + ($progst['net_amount'] * $progst['product_gst']/100);	
								$totgst = number_format((float)$totgst, 2, '.', '');
								$totwithgst = $totwithgst + $totgst;
							?>
							
								<tr class="gstrow" data-val="<?php echo $progst['product_gst']; ?>" id="gs_<?php echo $progst['product_gst']; ?>">
									<td class="border_right border_top" colspan="7" align="right" >GST @ <?php echo $progst['product_gst']; ?>%</td>
									<td class="border_right border_top" align="right"> <i class="<?php echo $quotationInfo->currency_faclass; ?>" style="font-size:13px;"></i>&nbsp; <span id='gstTotal_<?php echo $progst['product_gst']; ?>'><?php echo number_format((float)$totgst, 2, '.', ''); ?></span></td>
								</tr>
							
						<?php } ?>
						
						    <?php if($flagFreightGST==1 && $freight_gst>0){ 
								$perProFrchWthGst = ($freight_charge * $freight_gst)/100;
								$totgst = $perProFrchWthGst;
								$totgst = number_format((float)$totgst, 2, '.', '');
								$totwithgst = $totwithgst + $totgst;
							?>
								<tr>
									<td class="border_right border_top" colspan="7" align="right" ><b>GST @ <?php echo $freight_gst; ?>%</b></td>
									<td class="border_right border_top" align="right"> <i class="<?php echo $quotationInfo->currency_faclass; ?>" style="font-size:13px;"></i>&nbsp; <span id='gstTotal_<?php echo $freight_gst; ?>'><?php echo number_format((float)$totgst, 2, '.', ''); ?></span></td>
								</tr>
							<?php } ?>
						
						<?php } ?>
						<?php } ?>
					</tbody>
					<tr class="grndtr">
						<td class="border_right border_top" colspan="7" align="right" >Grand Total</td>
						<td class="border_right border_top" align="right"> <i class="<?php echo $quotationInfo->currency_faclass; ?>" style="font-size:13px;"></i>&nbsp; <span id="grand_total"><?php echo number_format((float)($net_total + $quotationInfo->freight_charge + $totwithgst), 2, '.', ''); ?></span></td>
					</tr>
				</table>
			</div>
			</br>
			<div class="row">
					<div class="col-sm-12" style="padding-right: 0px;padding-left: 0px;">
						<p style="margin: 0px;">Thank you for your interest in our company and products. We trust you will find the quote</p> 
						<p style="margin: 0px;">satisfactory. We look forward to your business.</p>						
					</div>					
				</div>
				<br>
				<div class="row">
					<div class="col-sm-12" style="padding-right: 0px;padding-left: 0px;">
						<p style="margin: 0px;">Remit to:</p>
					</div>
					
					<div class="col-sm-6" style="padding-right: 0px;padding-left: 0px;">					
						<div style="width:100%;float:left;">
							<p style="margin: 0px;width:40%;float:left;"><b>Payment :</b></p><p style="margin: 0px;float:left;">100% T/T(wire)</p>
						</div>	
						<div style="width:100%;float:left;">
							<p style="margin: 0px;width:40%;float:left;"><b>Beneficiary's Name:</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->beneficiary_name; ?></p>
						</div>
						
						<div style="width:100%;float:left;">
							<p style="margin: 0px;width:40%;float:left;"><b>Bank Name:</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->bank_name; ?></p>
						</div>
						
					</div>
					
					<div class="col-sm-6" style="padding-right: 0px;padding-left: 0px;">					
						<div style="width:100%;float:left;">
							<p style="margin: 0px;width:40%;float:left;"><b>Bank Details for</b></p><p style="margin: 0px;float:left;"> (<?php echo $quotationInfo->currency; ?>)</p>
						</div>	
						<div style="width:100%;float:left;">	
							<p style="margin: 0px;width:40%;float:left;"><b>Account No.:</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->account_number; ?></p>
						</div>
						
						<?php if($quotationInfo->currency == 'INR'){ ?>
							<?php if(!empty($bankInfo->ifsc_code)){ ?>
								<div style="width:100%;float:left;">
									<p style="margin: 0px;width:40%;float:left;"><b>IFSC Code :</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->ifsc_code; ?></p>
								</div>
							<?php } ?>
						<?php } else { ?>						
							<?php if(!empty($bankInfo->swift_code)){ ?>
								<div style="width:100%;float:left;">
									<p style="margin: 0px;width:40%;float:left;"><b>SWIFT Code :</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->swift_code; ?></p>
								</div>
							<?php } ?>	
						<?php } ?>						
					</div>
					
					<div class="col-sm-12" style="padding-right: 0px;padding-left: 0px;">					
						<div style="width:100%;float:left;">
							<p style="margin: 0px;width:20%;float:left;"><b>Bank Address :</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->bank_address; ?></p>
						</div>										
					</div>				
				
					<div class="col-sm-12" style="padding-right: 0px;padding-left: 0px;">						
						<p style="margin: 0px;">Bank remittance charge shall be paid by payer(buyer)</p><br>
						
					</div>									
				</div>
		</div>		
	</div>	
	</form>
	
	<div class="modal fade" id="orderpreviewmodel" role="dialog">
		<div class="modal-dialog" style="max-width: 1200px;">				
		  <!-- Modal content-->
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title">Order Preview</h4>
					<button type="button" class="close" data-dismiss="modal">&times;</button>			  
				</div>
				<div id="alert-danger"></div>
				<div class="modal-body">
					
					<div class="card mb-3">	
						<div class="card-body">
							<div class="row quote_view borderbox">
								<div class="col-sm-6 border_right">
									<p><b>Exporter:</b></p>
									<p><b>TARUN ENTERPRISES</b></p>
									<p><?php echo $quotationInfo->store_address; ?></p>
									<p>Phone: <?php echo $quotationInfo->store_phone; ?></p>
									<p>Email: <?php echo $quotationInfo->store_email; ?></p>
									<p>GST No: <?php echo $quotationInfo->store_gst_no; ?></p>
									<?php if($quotationInfo->store_name == 'Allahabad'){  ?>
										<p>Drug Licence: <?php echo $quotationInfo->drug_licence_no; ?></p>
										<p>Dt. <?php echo $quotationInfo->drug_date; ?></p>
									<?php } else { ?>
										<p>&nbsp;</p>						
									<?php } ?>
								</div>
								<div class="col-sm-6">
									<div class="row">
										<div class="col-sm-6 border_right border_bottom">
											<p><b>Quotation No:</b></p>
											<p style="margin-bottom: 15px;"><?php echo getQuotationNo($quotationInfo->quote_id); ?></p>
										</div>
										<div class="col-sm-6 border_bottom">
											<p><b>Quotation Date:</b></p>
											<p style="margin-bottom: 15px;"><?php echo date('F, d, Y', strtotime($quotationInfo->quotation_date)); ?></p>
										</div>
									</div>
									<div class="row">
										<div class="col-sm-6 border_right border_bottom">
											<p><b>Issued From:</b></p>
											<p style="margin-bottom: 15px;"><?php echo $quotationInfo->store_name; ?></p>
											
										</div>
										<div class="col-sm-6 border_bottom">
											<p><b>Currency:</b></p>
											<p style="margin-bottom: 15px;"><?php echo $quotationInfo->currency; ?></p>
											
										</div>
									</div>
									<div class="row">
										<div class="col-sm-6 border_right ">
											<p><b>Insurance:</b></p>
											<p style="margin-bottom: 15px;"><?php echo $quotationInfo->insurance; ?></p>
										</div>
										<div class="col-sm-6 ">
											<p><b>Generated by:</b></p>
											<p style="margin-bottom: 15px;"><?php echo $quotationInfo->firstname .' '.$quotationInfo->lastname; ?></p>
										</div>
									</div>
								</div>
								
								<div class="col-sm-6 border_top border_right">
									<p><b>Customer(Bill to):</b></p>
									<?php //echo nl2br($quotationInfo->billing_details); ?>									
									<textarea style="border: 0px solid #ced4da;background:white;" name="billingdetails" id="pre_bill_to" rows="8"  class="form-control" readonly><?php if($quotationInfo->billing_details) { echo $quotationInfo->billing_details; } ?></textarea>
								</div>
								
								<div class="col-sm-6 border_top">
									<p><b>Consingee(Ship to):</b></p>					
									<?php //echo nl2br($quotationInfo->shipping_details); ?>									
									<textarea style="border: 0px solid #ced4da;background:white;" name="shippingdetails" id="pre_ship_to" rows="8" class="form-control" readonly><?php if($quotationInfo->shipping_details) { echo $quotationInfo->shipping_details; } ?></textarea>
								</div>
								
								<div class="col-sm-6 border_top border_right border_bottom">
									<div class="row">
										<div class="col-sm-6 border_right">
											<p><b>Terms of Delivery:</b></p>
											<p style="margin-bottom: 15px;"><?php echo $quotationInfo->delivery; ?></p>
										</div>
										<div class="col-sm-6">
											<p><b>Terms of Payments:</b></p>
											<p style="margin-bottom: 15px;"><?php echo $quotationInfo->payment_terms; ?></p>
										</div>
									</div>
								</div>
								
								<div class="col-sm-6 border_top border_bottom">
									<p><b>Terms & Conditions:</b></p>
									<p style="margin-bottom: 15px;"><?php echo $quotationInfo->terms_conditions; ?></p>
								</div>
								
								<table class="table-sm table-bordered" id="priprotable" width="100%" cellspacing="0">
									<tr>
										<th class="border_right" style="width:4%;">S.N.</th>
										<th class="border_right" style="width:45.3%;">Product Description</th>
										<th class="border_right" style="width:10.5%;">HSN</th>
										<th class="border_right" style="width:6%;">Qty</th>
										<th class="border_right" style="width:6%;">Unit</th>
										<th class="border_right" style="width:6%;">Rate</th>
										<th class="border_right" style="width:12%;">Discount/Unit</th>
										<th style="width:9%;" align="right">Net Amount</th>
									</tr>
									
									<?php
										$net_total = 0;
										$i=1;
										foreach($quoteProductInfo as $productInfo){ 
										$net_total = $net_total + $productInfo['net_amount'];					
									?>								
										<tr class="preprotr" data-val="<?php echo $productInfo['prod_id'];?>">
											<td class="border_right border_top">&nbsp;&nbsp;<?php echo $i; ?></td>
											<td class="border_right border_top"><b><?php echo $productInfo['model_name']; ?></b> | <?php echo $productInfo['description']; ?></td>
											<td class="border_right border_top"><?php echo $productInfo['hsn']; ?></td>
											<td class="border_right border_top" ><span id="qty_<?php echo $productInfo['prod_id'];?>"><?php echo $productInfo['qty']; ?></span></td>
											<td class="border_right border_top"><?php echo $productInfo['unit']; ?></td>
											<td class="border_right border_top"><?php echo number_format((float)$productInfo['rate'], 4, '.', ''); ?></td>
											<td class="border_right border_top"><?php echo number_format((float)$productInfo['discount'], 4, '.', ''); ?></td>
											<td class="border_top" align="right"><span id="nmt_<?php echo $productInfo['prod_id'];?>"><?php echo number_format((float)$productInfo['net_amount'], 2, '.', ''); ?></span></td>
										</tr>
										
									<?php $i++; } ?>					
									<tr class="prenettottr">
										<td class="border_right border_top" colspan="7" align="right" >Net Total</td>
										<td class="border_right border_top" align="right"> <i class="<?php echo $quotationInfo->currency_faclass; ?>" style="font-size:13px;"></i>&nbsp; <span id="pre_net_total"><?php echo number_format((float)$net_total, 2, '.', ''); ?></span></td>
									</tr>
									<tr class="preftr">
										<td class="border_right border_top" colspan="7" align="right" >Freight Charges</td>
										<td class="border_right border_top" align="right"> <i class="<?php echo $quotationInfo->currency_faclass; ?>" style="font-size:13px;"></i>&nbsp; 
										<span id="pre_freight_charge"><?php echo number_format((float)$quotationInfo->freight_charge, 2, '.', ''); ?></span></td>
									</tr>
									<tbody id="preprogstall">
											<?php
												if(($quotationInfo->currency == 'INR') && ($customerInfo->countryId == '99')){
												if($productgst){												
												$totwithgst = 0;
												$freight_charge = $quotationInfo->freight_charge;
												$freight_gst = $this->config->item('PER_FREIGHT_GST');
        										$flagFreightGST=1;# set 0 if GST% of freight charge is in the list of products.
        										#i.e to cheate the row for GST @ 18% (Freight GST)
												foreach($productgst as $progst){
													/* $perProFrch = ($freight_charge / $net_total) * $progst['net_amount'];
                    								$perProFrchWthGst = ($perProFrch * $progst['product_gst']/100);
                    								$totgst = $perProFrchWthGst + ($progst['net_amount'] * $progst['product_gst']/100);								
                    								$totwithgst = $totwithgst + $totgst; */
                    								
                    								if($freight_gst==0){
                    									$perProFrch = ($freight_charge / $net_total) * $progst['net_amount'];
                    									$perProFrchWthGst = ($perProFrch * $progst['product_gst']/100);
                    								}else if(!empty($freight_gst)){
                    									if($freight_gst==$progst['product_gst']){
                    										$perProFrchWthGst = ($freight_charge * $freight_gst)/100;
                    										$flagFreightGST=0;
                    									}
                    								}
                    
                    								$totgst = $perProFrchWthGst + ($progst['net_amount'] * $progst['product_gst']/100);	
                    								$totgst = number_format((float)$totgst, 2, '.', '');
                    								$totwithgst = $totwithgst + $totgst;
											?>
											
												<tr class="pregstrow" data-val="<?php echo $progst['product_gst']; ?>" id="pregs_<?php echo $progst['product_gst']; ?>">
													<td class="border_right border_top" colspan="7" align="right" >GST @ <?php echo $progst['product_gst']; ?>%</td>
													<td class="border_right border_top" align="right"> <i class="<?php echo $quotationInfo->currency_faclass; ?>" style="font-size:13px;"></i>&nbsp; <span id='pregstTotal_<?php echo $progst['product_gst']; ?>'><?php echo number_format((float)$totgst, 2, '.', ''); ?></span></td>
												</tr>
											
										<?php } ?>
										
										<?php if($flagFreightGST==1 && $freight_gst>0){ 
            								$perProFrchWthGst = ($freight_charge * $freight_gst)/100;
            								$totgst = $perProFrchWthGst;
            								$totgst = number_format((float)$totgst, 2, '.', '');
            								$totwithgst = $totwithgst + $totgst;
            							?>
            								<tr>
            									<td class="border_right border_top" colspan="7" align="right" ><b>GST @ <?php echo $freight_gst; ?>%</b></td>
            									<td class="border_right border_top" align="right"> <i class="<?php echo $quotationInfo->currency_faclass; ?>" style="font-size:13px;"></i>&nbsp; <?php echo number_format((float)$totgst, 2, '.', ''); ?></td>
            								</tr>
            							<?php } ?>
										
									<?php } ?>
									<?php } ?>
									</tbody>
									<tr class="pregrndtr">
										<td class="border_right border_top" colspan="7" align="right" >Grand Total</td>
										<td class="border_right border_top" align="right"> <i class="<?php echo $quotationInfo->currency_faclass; ?>" style="font-size:13px;"></i>&nbsp; <span id="pre_grand_total"><?php echo number_format((float)($net_total + $quotationInfo->freight_charge + $totwithgst), 2, '.', ''); ?></span></td>
									</tr>
								</table>
							</div>
							<br>
							<div class="row">
								<div class="col-sm-12">
									<button type="button" id="saveOrder" class="btn btn-primary float-right" data-toggle="tooltip" data-placement="top" title="Save Order"> <!-- <i class="fas fa-save"></i> --> Save Order</button>
								</div>
							</div>
							<div class="row">
								<div class="col-sm-12" style="padding-right: 0px;padding-left: 0px;">
									<p style="margin: 0px;">Thank you for your interest in our company and products. We trust you will find the quote</p> 
									<p style="margin: 0px;">satisfactory. We look forward to your business.</p>
									<p style="margin: 0px;">Goods are of OPTITECH brand. Made in India.</p>
								</div>					
							</div>
							<br>
							<div class="row">
								<div class="col-sm-12" style="padding-right: 0px;padding-left: 0px;">
										<p style="margin: 0px;">Remit to:</p>
									</div>
									
									<div class="col-sm-6" style="padding-right: 0px;padding-left: 0px;">					
										<div style="width:100%;float:left;">
											<p style="margin: 0px;width:40%;float:left;"><b>Payment :</b></p><p style="margin: 0px;float:left;">100% T/T(wire)</p>
										</div>	
										<div style="width:100%;float:left;">
											<p style="margin: 0px;width:40%;float:left;"><b>Beneficiary's Name:</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->beneficiary_name; ?></p>
										</div>
										
										<div style="width:100%;float:left;">
											<p style="margin: 0px;width:40%;float:left;"><b>Bank Name:</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->bank_name; ?></p>
										</div>
										
									</div>
									
									<div class="col-sm-6" style="padding-right: 0px;padding-left: 0px;">					
										<div style="width:100%;float:left;">
											<p style="margin: 0px;width:40%;float:left;"><b>Bank Details for</b></p><p style="margin: 0px;float:left;"> (<?php echo $quotationInfo->currency; ?>)</p>
										</div>	
										<div style="width:100%;float:left;">	
											<p style="margin: 0px;width:40%;float:left;"><b>Account No.:</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->account_number; ?></p>
										</div>
										
										<?php if($quotationInfo->currency == 'INR'){ ?>
											<?php if(!empty($bankInfo->ifsc_code)){ ?>
												<div style="width:100%;float:left;">
													<p style="margin: 0px;width:40%;float:left;"><b>IFSC Code :</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->ifsc_code; ?></p>
												</div>
											<?php } ?>
										<?php } else { ?>						
											<?php if(!empty($bankInfo->swift_code)){ ?>
												<div style="width:100%;float:left;">
													<p style="margin: 0px;width:40%;float:left;"><b>SWIFT Code :</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->swift_code; ?></p>
												</div>
											<?php } ?>	
										<?php } ?>						
									</div>
									
									<div class="col-sm-12" style="padding-right: 0px;padding-left: 0px;">					
										<div style="width:100%;float:left;">
											<p style="margin: 0px;width:20%;float:left;"><b>Bank Address :</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->bank_address; ?></p>
										</div>										
									</div>				
								
									<div class="col-sm-12" style="padding-right: 0px;padding-left: 0px;">						
										<p style="margin: 0px;">Bank remittance charge shall be paid by payer(buyer)</p><br>
										
									</div>					
							</div>
						</div>		
					</div>
					
					
				</div>
			</div>
		</div>
	</div>	
	
</div>
<script>
	$(document).ready(function() {
		/* var allGst=0;
		$(".classPrototgst").each(function(){
			allGst=allGst+parseFloat($(this).html());
			//alert(allGst);
		}); */
		
		//Preview Popup
		
		var freight_gst = '<?php echo $this->config->item('PER_FREIGHT_GST'); ?>';
		
		$("#priviewOrder").click(function(){
			
			var currency = '<?php echo $quotationInfo->currency; ?>';
			var country_id = '<?php echo $customerInfo->countryId; ?>';
			var chkbox = '';
			var chkval = ''
			var prenettot = 0;
			var priprototal = '';
			var prefreight_charge = '';
			var pregrand_tot = '';
			var gstArr={};
			
			var billing_details = $("#billing_details").val(); 
			var shipping_details = $("#shipping_details").val(); 
			$("#pre_bill_to").val(billing_details);
			$("#pre_ship_to").val(shipping_details);			
			
			$(".prtr").each(function(){
				chkbox = $(this).find('input[type="checkbox"]');
				var id = chkbox.val();
				
				if(chkbox.prop("checked")==false){					
					$('#priprotable').find("[data-val='"+ id +"']").remove();					
				} else if(chkbox.prop("checked")==true) {					
					var qty = $(this).find('input[type="text"]').val();
						$("#qty_"+id).html(qty);
					var rate = $(this).find("td:eq(5)").html();
					
					var discount = $(this).find("td:eq(6)").html();
					
					var net_amount = parseFloat(rate) - parseFloat(discount);
					
					net_amount = parseFloat(net_amount.toFixed(4)) * parseInt(qty);
					
					$("#nmt_"+id).html(net_amount.toFixed(2));
					
					$(this).find("td:eq(7)").html(net_amount.toFixed(2));
					
					var gstName="gst_"+id;
					var gstRate=$("#"+gstName).val();
					var gstAmt="gstAmt_"+id;
					if(gstArr[gstRate]==null){
						gstArr[gstRate]=0.00;
					}	
					
					priprototal = $(this).find("td:last").html();
					var gstAmount = 0.00;
					if((currency == 'INR') && (country_id == '99')){						
						gstAmount=(priprototal*gstRate)/100;
						gstArr[gstRate]=parseFloat(gstArr[gstRate])+parseFloat(gstAmount);	
						//gstArr[gstRate]=priprototal;	
					}						
					prenettot = parseFloat(prenettot) + parseFloat(priprototal);
				}				
			});
			
			prenettot = prenettot.toFixed(2);			
			$("#pre_net_total").html(prenettot);
			prefreight_charge = $("#freight_charge").html();
			$("#pre_freight_charge").html(prefreight_charge);
			
			pregrand_tot = parseFloat(prenettot) + parseFloat(prefreight_charge);
			
			//if(currency == 'INR'){
			if((currency == 'INR') && (country_id == '99')){
				var htm2 = '';
				var perProFrch = 0;
				var gstFlag = 0;
				$.each(gstArr , function(index, val) {
				    if(index==''){
						return true;
					}
					//perProFrch = (parseFloat(prefreight_charge) / parseFloat(prenettot)) * parseFloat(val);						
					//val = parseFloat(perProFrch) + parseFloat(val);
					
					if(freight_gst == index){
                    	gstFlag = 1;
                    	var gtval = (parseFloat(prefreight_charge) * parseFloat(freight_gst)) / 100;
                    	val = val + gtval;
                    }
					
					htm2 += '<tr class="pregstrow" data-val='+index+' id="pregs_'+index+'">';	
					htm2 += '<td  style="border-right:2px solid gray;border-top:2px solid gray;" colspan="7" align="right">GST @ '+index+' %</td>';
					htm2 += '<td style="border-right:2px solid gray;border-top:2px solid gray;" align="right"><span id="pregstTotal_'+index+'"><i class="fas fa-rupee-sign" style="font-size:13px;"></i>&nbsp;'+val.toFixed(2)+'</span></td>';
					htm2 += '</tr>';
					
					
					
					var gstTotal="pregstTotal_"+index;
					$("#"+gstTotal).html(val.toFixed(2));
					pregrand_tot=parseFloat(pregrand_tot)+parseFloat(val);
				});
				
				if(freight_gst > 0 && gstFlag == 0){
                	var gtval1 = (parseFloat(prefreight_charge) * parseFloat(freight_gst)) / 100;
                	
                	htm2 += '<tr class="pregstrow" data-val='+freight_gst+' id="pregs_'+freight_gst+'">';	
					htm2 += '<td  style="border-right:2px solid gray;border-top:2px solid gray;" colspan="7" align="right">GST @ '+freight_gst+' %</td>';
					htm2 += '<td style="border-right:2px solid gray;border-top:2px solid gray;" align="right"><span id="pregstTotal_'+freight_gst+'"><i class="fas fa-rupee-sign" style="font-size:13px;"></i>&nbsp;'+gtval1.toFixed(2)+'</span></td>';
					htm2 += '</tr>';
                	
                	pregrand_tot = parseFloat(pregrand_tot) + parseFloat(gtval1);
                }
				
				
				 $("#preprogstall").html(htm2);
			 }
			
			$("#pre_grand_total").html(pregrand_tot.toFixed(2));			
			$("#orderpreviewmodel").modal();				
		});
		
		
		
		
		$("#saveOrder").click(function(){
		    $('#saveOrder').prop('disabled', true);
			 $("#saveOrderForm").submit();
		});
		//End Preview Popup
		
		$('.procheckbox').click(function() {			
			var currency = '<?php echo $quotationInfo->currency; ?>';
			var country_id = '<?php echo $customerInfo->countryId; ?>';
			if (!$(this).is(':checked')) {
				var val = $(this).val();
				var gstPer=$('#gst_'+val).val();
				var nettot = 0;
				var prototal = 0;
				var grand_tot = 0;
				var freight_charge = 0;
				var chkbox = '';
				var gstArr1={};				
				$(".prtr").each(function(){
					chkbox = $(this).find('input[type="checkbox"]');					
					if(chkbox.prop('checked')){						
						var id= chkbox.prop('id');					
						var res = id.split("_");
						var pro_id=res[1];
						var gstName="gst_"+pro_id;
						var gstRate=$("#"+gstName).val();
						var gstAmt="gstAmt_"+pro_id;
						if(gstArr1[gstRate]==null){
							gstArr1[gstRate]=0.00;
						}				
						
						prototal = $(this).find("td:last").html();
						nettot = parseFloat(nettot) + parseFloat(prototal);
						var gstAmount=0.00;
						//if(currency == 'INR'){
						if((currency == 'INR') && (country_id == '99')){
							gstAmount=(prototal*gstRate)/100;
							gstArr1[gstRate]=parseFloat(gstArr1[gstRate])+parseFloat(gstAmount);	
							//gstArr1[gstRate]=prototal;	
						}												
					} 
				});
				
				/* if(currency == 'INR'){
					$(".gstrow").each(function(){
						var id = this.id;
						var res = id.split("_");
						var gst = res[1];
						alert(gst);
						//$('#protable').find("[data-val='"+ gst +"']").remove();					
					});
				} */
				
				nettot = nettot.toFixed(2);				
				$("#net_total").html(nettot);				
				freight_charge = $("#freight_charge").html();				
				grand_tot = parseFloat(nettot) + parseFloat(freight_charge);
				
				//if(currency == 'INR'){
				if((currency == 'INR') && (country_id == '99')){
					var htm2 = '';
					var perProFrch = 0;
					var gstFlag = 0;
					$.each(gstArr1 , function(index, val) {
						//perProFrch = (parseFloat(freight_charge) / parseFloat(nettot)) * parseFloat(val);						
						//val = parseFloat(perProFrch) + parseFloat(val);
						
						if(freight_gst == index){
                        	gstFlag = 1;
                        	var gtval = (parseFloat(prefreight_charge) * parseFloat(freight_gst)) / 100;
                        	val = val + gtval;
                        }
					
						htm2 += '<tr class="gstrow" data-val='+index+' id="gs_'+index+'">';	
						htm2 += '<td  style="border-right:2px solid gray;border-top:2px solid gray;" colspan="7" align="right">GST @ '+index+' %</td>';
						htm2 += '<td style="border-right:2px solid gray;border-top:2px solid gray;" align="right"><span id="gstTotal_'+index+'"><i class="fas fa-rupee-sign" style="font-size:13px;"></i>&nbsp;'+val.toFixed(2)+'</span></td>';
						htm2 += '</tr>';
						
					
						
						var gstTotal="gstTotal_"+index;
						$("#"+gstTotal).html(val.toFixed(2));
						grand_tot=parseFloat(grand_tot)+parseFloat(val);
					});
					
					if(freight_gst > 0 && gstFlag == 0){
                    	var gtval1 = (parseFloat(freight_charge) * parseFloat(freight_gst)) / 100;
                    	
                    	htm2 += '<tr class="gstrow" data-val='+freight_gst+' id="gs_'+freight_gst+'">';	
						htm2 += '<td  style="border-right:2px solid gray;border-top:2px solid gray;" colspan="7" align="right">GST @ '+freight_gst+' %</td>';
						htm2 += '<td style="border-right:2px solid gray;border-top:2px solid gray;" align="right"><span id="gstTotal_'+freight_gst+'"><i class="fas fa-rupee-sign" style="font-size:13px;"></i>&nbsp;'+gtval1.toFixed(2)+'</span></td>';
						htm2 += '</tr>';
                    	
                    	grand_tot = parseFloat(grand_tot) + parseFloat(gtval1);
                    }
					
					 $("#progstall").html(htm2);
				}
				
				$("#grand_total").html(grand_tot.toFixed(2));
				
			} else if($(this).is(':checked')) {
				
				var val = $(this).val();
				var gstPer=$('#gst_'+val).val();
				var nettot1 = 0;
				var prototal1 = 0;
				var grand_tot1 = 0;
				var freight_charge1 = 0;
				var chkbox = '';
				var gstArr={}; 				
				$(".prtr").each(function(){
					chkbox = $(this).find('input[type="checkbox"]');					
					if(chkbox.prop('checked')){						
						var id= chkbox.prop('id');					
						var res = id.split("_");
						var pro_id=res[1];
						var gstName="gst_"+pro_id;
						var gstRate=$("#"+gstName).val();
						var gstAmt="gstAmt_"+pro_id;
						if(gstArr[gstRate]==null){
							gstArr[gstRate]=0.00;
						}						
						prototal1 = $(this).find("td:last").html();
						nettot1 = parseFloat(nettot1) + parseFloat(prototal1);
						
						var gstAmount=0.00;
						//if(currency == 'INR'){
						if((currency == 'INR') && (country_id == '99')){
							gstAmount=(prototal1*gstRate)/100;
							gstArr[gstRate]=parseFloat(gstArr[gstRate])+parseFloat(gstAmount);
						}												
					} 
				});
				
				/* if(currency == 'INR'){
					$(".gstrow").each(function(){
						var id = this.id;
						var res = id.split("_");
						var gst = res[1];
						//$('#protable').find("[data-val='"+ gst +"']").remove();					
					});
				} */

				nettot1 = nettot1.toFixed(2);	
				
				$("#net_total").html(nettot1);				
				freight_charge1 = $("#freight_charge").html();				
				grand_tot1 = parseFloat(nettot1) + parseFloat(freight_charge1);
				
				//if(currency == 'INR'){
				if((currency == 'INR') && (country_id == '99')){
					var htm2 = '';
					var perProFrch = 0;
					var gstFlag = 0;
					$.each(gstArr , function(index, val) {						
						//perProFrch = (parseFloat(freight_charge1) / parseFloat(nettot1)) * parseFloat(val);						
						//val = parseFloat(perProFrch) + parseFloat(val);
						
						if(freight_gst == index){
                        	gstFlag = 1;
                        	var gtval = (parseFloat(freight_charge1) * parseFloat(freight_gst)) / 100;
                        	val = val + gtval;
                        }
						
						htm2 += '<tr class="gstrow" data-val='+index+' id="gs_'+index+'">';	
						htm2 += '<td  style="border-right:2px solid gray;border-top:2px solid gray;" colspan="7" align="right">GST @ '+index+' %</td>';
						htm2 += '<td style="border-right:2px solid gray;border-top:2px solid gray;" align="right"><span id="gstTotal_'+index+'"><i class="fas fa-rupee-sign" style="font-size:13px;"></i>&nbsp;'+val.toFixed(2)+'</span></td>';
						htm2 += '</tr>';
						
						
						
						var gstTotal="gstTotal_"+index;
						$("#"+gstTotal).html(val.toFixed(2));
						grand_tot1=parseFloat(grand_tot1)+parseFloat(val);
					});	
					
					
					if(freight_gst > 0 && gstFlag == 0){
                    	var gtval1 = (parseFloat(freight_charge) * parseFloat(freight_gst)) / 100;
                    	
                    	htm2 += '<tr class="gstrow" data-val='+freight_gst+' id="gs_'+freight_gst+'">';	
						htm2 += '<td  style="border-right:2px solid gray;border-top:2px solid gray;" colspan="7" align="right">GST @ '+freight_gst+' %</td>';
						htm2 += '<td style="border-right:2px solid gray;border-top:2px solid gray;" align="right"><span id="gstTotal_'+freight_gst+'"><i class="fas fa-rupee-sign" style="font-size:13px;"></i>&nbsp;'+gtval1.toFixed(2)+'</span></td>';
						htm2 += '</tr>';
                    	
                    	grand_tot1 = parseFloat(grand_tot1) + parseFloat(gtval1);
                    }
					
					$("#progstall").html(htm2);
				}
				$("#grand_total").html(grand_tot1.toFixed(2));				
			}			
		});
		
		$('#freightcharge').keyup(function() {
			var currency = '<?php echo $quotationInfo->currency; ?>';
			var country_id = '<?php echo $customerInfo->countryId; ?>';
			var freightcharge = $(this).val();
			freightcharge = parseFloat(freightcharge).toFixed(2);
			if(freightcharge == 'NaN'){
				freightcharge = '00.00';
			}
			
			$("#freight_charge").html(freightcharge);				
			var nettot = 0;
			var prototal = '';
			var grand_tot = '';
			var freight_charge = '';
			var chkbox = '';
			var gstArr={};
			$(".prtr").each(function(){
				chkbox = $(this).find('input[type="checkbox"]');					
				if(chkbox.prop('checked')){
					var id= chkbox.prop('id');					
					var res = id.split("_");
					var pro_id=res[1];
					var gstName="gst_"+pro_id;
					var gstRate=$("#"+gstName).val();
					var gstAmt="gstAmt_"+pro_id;
					if(gstArr[gstRate]==null){
						gstArr[gstRate]=0.00;
					}
					
					prototal = $(this).find("td:last").html();						
					nettot = parseFloat(nettot) + parseFloat(prototal);
					
					var gstAmount=0.00;
					//if(currency == 'INR'){
					if((currency == 'INR') && (country_id == '99')){
						gstAmount=(prototal*gstRate)/100;					
						gstArr[gstRate]=parseFloat(gstArr[gstRate])+parseFloat(gstAmount);
						//gstArr[gstRate]=prototal;
					}
				}
			});	
			nettot = nettot.toFixed(2);
			$("#net_total").html(nettot);				
			freight_charge = freightcharge;	
			
			grand_tot = parseFloat(nettot) + parseFloat(freight_charge);
			
			//if(currency == 'INR'){
			if((currency == 'INR') && (country_id == '99')){
				var perProFrch = 0;
				var gstFlag = 0;
				$.each(gstArr , function(index, val) {
					//perProFrch = (parseFloat(freight_charge) / parseFloat(nettot)) * parseFloat(val);						
					//val = parseFloat(perProFrch) + parseFloat(val);
					
					if(freight_gst == index){
                    	gstFlag = 1;
                    	var gtval = (parseFloat(freight_charge) * parseFloat(freight_gst)) / 100;
                    	val = val + gtval;
                    }
					
					var gstTotal="gstTotal_"+index;
					$("#"+gstTotal).html(val.toFixed(2));
					grand_tot=parseFloat(grand_tot)+parseFloat(val);
				});
				if(freight_gst > 0 && gstFlag == 0){
                	var gtval1 = (parseFloat(freight_charge) * parseFloat(freight_gst)) / 100;
                	var gstTotal1="gstTotal_"+freight_gst;
                	$("#"+gstTotal1).html(gtval1);
                	grand_tot = parseFloat(grand_tot) + parseFloat(gtval1);
                }
			}
			
			$("#grand_total").html(grand_tot.toFixed(2));			
		});	
		
		//Qty
		$('.qty').keyup(function() {
			var currency = '<?php echo $quotationInfo->currency; ?>';
			var country_id = '<?php echo $customerInfo->countryId; ?>';
			var qty = $(this).val();			
			var rate = $(this).closest('tr').find("td:eq(5)").html();			
			var discount = $(this).closest('tr').find("td:eq(6)").html();			
			var net_amount = parseFloat(rate) - parseFloat(discount);
			net_amount = parseFloat(net_amount) * parseFloat(qty);
			$(this).closest('tr').find("td:eq(7)").html(net_amount.toFixed(2));
			
			var result = (this.id).split('_');
			var product_id = result[1];
			$("#proamt_"+product_id).val(net_amount.toFixed(2));
			
			var nettot = 0;
			var prototal = '';
			var grand_tot = '';
			var freight_charge = '';
			var chkbox = '';
			var gstArr={};			
			$(".prtr").each(function(){
				chkbox = $(this).find('input[type="checkbox"]');					
				if(chkbox.prop('checked')){
					var id= chkbox.prop('id');					
					var res = id.split("_");
					var pro_id=res[1];
					var gstName="gst_"+pro_id;
					var gstRate=$("#"+gstName).val();
					var gstAmt="gstAmt_"+pro_id;
					if(gstArr[gstRate]==null){
						gstArr[gstRate]=0.00;
					}
					
					prototal = $(this).find("td:last").html();					
					nettot = parseFloat(nettot) + parseFloat(prototal);
					
					var gstAmount=0.00;
					//if(currency == 'INR'){
					if((currency == 'INR') && (country_id == '99')){
						gstAmount=(prototal*gstRate)/100;					
						gstArr[gstRate]=parseFloat(gstArr[gstRate])+parseFloat(gstAmount);
						//gstArr[gstRate]=prototal;
					}					
				}
			});	
			nettot = nettot.toFixed(2);
			$("#net_total").html(nettot);				
			freight_charge = $("#freight_charge").html();				
			grand_tot = parseFloat(nettot) + parseFloat(freight_charge);
			
			//if(currency == 'INR'){
			if((currency == 'INR') && (country_id == '99')){
				var perProFrch = 0;
				var gstFlag = 0;
				$.each(gstArr , function(index, val) {
					//perProFrch = (parseFloat(freight_charge) / parseFloat(nettot)) * parseFloat(val);						
					//val = parseFloat(perProFrch) + parseFloat(val);
					
					if(freight_gst == index){
                    	gstFlag = 1;
                    	var gtval = (parseFloat(freight_charge) * parseFloat(freight_gst)) / 100;
                    	val = val + gtval;
                    }
					
					var gstTotal="gstTotal_"+index;
					$("#"+gstTotal).html(val.toFixed(2));
					grand_tot=parseFloat(grand_tot)+parseFloat(val);
				});
				
				if(freight_gst > 0 && gstFlag == 0){
                	var gtval1 = (parseFloat(freight_charge) * parseFloat(freight_gst)) / 100;
                	
                	var gstTotal1="gstTotal_"+freight_gst;
					$("#"+gstTotal1).html(gtval1);
                	
                	grand_tot = parseFloat(grand_tot) + parseFloat(gtval1);
                }
				
			}
			
			$("#grand_total").html(grand_tot.toFixed(2));
			
		});

		$('#billing_details_default').change(function() {
			var address_id = $("#billing_details_default option:selected").val();
			if(address_id == ''){
				$("#billing_details").val('');
				return false;
			}
			var customer_id = '<?php echo $customerInfo->customer_id; ?>';			
			$.ajax({
				url:'<?php echo site_url('getAddressByAddressId');?>',
				method: 'post',					
				data: {address_id: address_id, customer_id: customer_id},
				dataType: 'json',
				success: function(response){						
					var company_name1 			= (response.company_name) ? response.company_name : '';
					var contact_person1 		= (response.contact_person) ? "\n" + response.contact_person : '';
					var address_11 				= (response.address_1) ? "\n" + response.address_1 : '';
					var address_21 				= (response.address_2) ? "\n" +response.address_2 : '';
					var city1 					= (response.city) ? "\n" +response.city : '';						
					var district1 				= (response.district) ? "," +response.district : '';
					var state1 					= (response.state_name) ? "," +response.state_name : '';
					var pin1 					= (response.pin) ? "\n" +response.pin : '';
					var country1 				= (response.country_name) ? "," +response.country_name : '';
					var phone1 					= (response.phone) ? " " + response.phone : '';
					var mobile1 				= (response.mobile) ? " " + response.mobile : '';
					
					var mob = '';
					if(phone1 && mobile1){ 
						mob = "\nMobile: "+phone1 + ", "+mobile1;
					}else if((phone1) && (mobile1 == '')) {
						mob = "\nMobile: "+phone1;
					} else if((mobile1) && (phone1 == '')){
						mob = "\nMobile: "+mobile1;
					}
					var email1 					= (response.email) ? "\nEmail: " +response.email : '';						
				
					var billing_address = company_name1 + address_11 + address_21 + city1 + district1 + state1 + pin1 + country1 + mob + email1 + contact_person1;	
					
					$("#billing_details").val(billing_address);
				}
			});				
		});
		
		$('#shipping_details_default').change(function() {
			$("#same_address").prop('checked', false);
			var address_id = $("#shipping_details_default option:selected").val();
			if(address_id == ''){
				$("#shipping_details").val('');
				return false;
			}
			var customer_id = '<?php echo $customerInfo->customer_id; ?>';			
			$.ajax({
				url:'<?php echo site_url('getAddressByAddressId');?>',
				method: 'post',					
				data: {address_id: address_id, customer_id: customer_id},
				dataType: 'json',
				success: function(response){						
					var company_name1 			= (response.company_name) ? response.company_name : '';
					var contact_person1 		= (response.contact_person) ? "\n" + response.contact_person : '';
					var address_11 				= (response.address_1) ? "\n" + response.address_1 : '';
					var address_21 				= (response.address_2) ? "\n" +response.address_2 : '';
					var city1 					= (response.city) ? "\n" +response.city : '';						
					var district1 				= (response.district) ? "," +response.district : '';
					var state1 					= (response.state_name) ? "," +response.state_name : '';
					var pin1 					= (response.pin) ? "\n" +response.pin : '';
					var country1 				= (response.country_name) ? "," +response.country_name : '';
					var phone1 					= (response.phone) ? " " + response.phone : '';
					var mobile1 				= (response.mobile) ? " " + response.mobile : '';
					
					var mob = '';
					if(phone1 && mobile1){ 
						mob = "\nMobile: "+phone1 + ", "+mobile1;
					}else if((phone1) && (mobile1 == '')) {
						mob = "\nMobile: "+phone1;
					} else if((mobile1) && (phone1 == '')){
						mob = "\nMobile: "+mobile1;
					}
					
					
					var email1 					= (response.email) ? "\nEmail: " +response.email : '';						
				
					var shipping_details = company_name1 + address_11 + address_21 + city1 + district1 + state1 + pin1 + country1 + mob + email1 + contact_person1;	
					
					$("#shipping_details").val(shipping_details);
				}			
			});
		});
		
		$("#same_address").on("click", function () {			
			if($(this).is(":checked")) {
				 $("#shipping_details").val($("#billing_details").val());   
		    } else {
				$("#shipping_details").val('');  
			}			
		});		
	});	
		
</script>