<?php
defined('BASEPATH') OR exit('No direct script access allowed');
?>
<div style="padding-right: 25px;padding-left: 25px;font-size:12px;padding-bottom: 50px;">		
		
			<div style="border-top:0px solid black;border-left:2px solid black;border-right:2px solid black;">
				<div style="border-right: 2px solid black;width: 50%;float:left;padding:3px;" >
					<div style="width:100%;float:left;"><b>Exporter:</b></div>
					<div style="width:100%;float:left;"><b>TARUN ENTERPRISES</b></div>
					<div style="width:100%;float:left;"><?php echo $ordersInfo->store_address; ?></div>
					<div style="width:100%;float:left;">Phone: <?php echo $ordersInfo->store_phone; ?></div>
					<div style="width:100%;float:left;">Email: <?php echo $ordersInfo->store_email; ?></div>
					<div style="width:100%;float:left;">GST No: <?php echo $ordersInfo->store_gst_no; ?></div>
					
					<?php if($ordersInfo->store_name == 'Allahabad'){  ?>						
						<div style="width:100%;float:left;">Drug Licence: <?php echo $ordersInfo->drug_licence_no; ?></div>
						<div style="width:100%;float:left;">Dt. <?php echo $ordersInfo->drug_date; ?></div>
					<?php } else { ?>
						<div style="width:100%;float:left;">&nbsp;</div>						
					<?php } ?>					
				</div>
				
				<div style="float:left;">
					<div class="row">
						<div style="width:50%;float:left;border-right:2px solid black;border-bottom:2px solid black;height:38px;padding:3px;">
							<div style="width:100%;float:left;"><b>Order No:</b></div>
							<div style="width:100%;float:left;"><?php echo getOrderNo($ordersInfo->order_id); ?></div>
						</div>
						<div style="border-bottom:2px solid black;float:left;height:38px;padding:3px;">
							<div style="width:100%;float:left;"><b>Order Date:</b></div>
							<div style="width:100%;float:left;"><?php echo dateFormat('F, d, Y', $ordersInfo->order_date); ?></div>
						</div>
					</div>
					<div class="row">
						<div style="border-right:2px solid black;border-bottom:2px solid black;width: 50%;float:left;height:38px;padding:3px;">
							<div style="width:100%;float:left;"><b>Issued From:</b></div>
							<div style="width:100%;float:left; "><?php echo $ordersInfo->store_name; ?></div>
							
						</div>
						<div style="border-bottom:2px solid black;float:left;height:38px;padding:3px;">
							<div style="width:100%;float:left;"><b>Currency:</b></div>
							<div style="width:100%;float:left;"><?php echo $ordersInfo->currency; ?></div>
							
						</div>
					</div>
					<div class="row">
						<div style="border-right:2px solid black;width:50%;float:left;height:40px;padding:3px;">
							<div style="width:100%;float:left;"><b>Insurance:</b></div>
							<div style="width:100%;float:left;"><?php echo $ordersInfo->insurance; ?></div>
						</div>
						<div  style="float:left;height:40px;padding:3px;">
							<div style="width:100%;float:left;"><b>Generated by:</b></div>
							<div style="width:100%;float:left;"><?php echo $ordersInfo->firstname .' '.$ordersInfo->lastname; ?></div>
						</div>
					</div>
				</div>
				
				<div style="width: 50.4%;float:left;border-top:2px solid black; border-right:2.3px solid black;padding-left:3px;">
					<div style="width:100%;float:left;"><b>Customer(Bill to):</b></div>
					<div style="width:100%;float:right;">
					<?php $billingAddress=nl2br($ordersInfo->billing_details);
						while(preg_match("/(.*?)\n/is",$billingAddress,$matcher)){
							print "<b>$matcher[1]</b>";
							$billingAddress=after($matcher[0],$billingAddress);
							break;
						}
					?>
					<?php echo $billingAddress; ?></div>					
					
					<?php if($customerInfo->gst){ ?>
					<div style="width:100%;float:left;">GST No.: <?php echo $customerInfo->gst; ?></div>
					<?php } ?>
					<?php if($customerInfo->company_registration_no){ ?>
					<div style="width:100%;float:left;">Reg. No.: <?php echo $customerInfo->company_registration_no; ?></div>
					<?php } ?>
					<?php if($customerInfo->drug_licence_no){ ?>
					<div style="width:100%;float:left;">Drug Licence no.: <?php echo $customerInfo->drug_licence_no; ?></div>
					<?php } ?>
				</div>
				
				<div style="border-top:2px solid black;float:left;padding-left:3px;">
					<div style="width:100%;float:left;"><b>Consingee(Ship to):</b></div>					
					<div style="width:100%;float:left;">
						<?php $shippingAddress=nl2br($ordersInfo->shipping_details);
						while(preg_match("/(.*?)\n/is",$shippingAddress,$matcher)){
							print "<b>$matcher[1]</b>";
							$shippingAddress=after($matcher[0],$shippingAddress);
							break;
						}
					?>
					<?php echo $shippingAddress; ?>					
					
					</div>
					<?php if($customerInfo->gst){ ?>
					<div style="width:100%;float:left;">GST No.: <?php echo $customerInfo->gst; ?></div>
					<?php } ?>
					<?php if($customerInfo->company_registration_no){ ?>
					<div style="width:100%;float:left;">Reg. No.: <?php echo $customerInfo->company_registration_no; ?></div>
					<?php } ?>	
					<?php if($customerInfo->drug_licence_no){ ?>
					<div style="width:100%;float:left;">Drug Licence no.: <?php echo $customerInfo->drug_licence_no; ?></div>
					<?php } ?>
				</div>
				
				<?php
					$delivery = str_word_count($ordersInfo->delivery);
					$payment_terms = str_word_count($ordersInfo->payment_terms);
					$x=0;
					$y=0;
					if($delivery > $payment_terms){
						$x=2;
					} else if($payment_terms > $delivery) {
						$y=2;
					} else {
						$x = 2;
					}
				?>		
				
				<div style="border-top:2px solid black;width:100%;float:left;">
					<div class="row">
						<div style="width:50.8%;float:left;border-right:<?php echo $x; ?>px solid black;">
							<div style="width:100%;float:left;padding-left:3px;"><b>Terms of Delivery:</b> <?php echo $ordersInfo->delivery; ?></div>
							
						</div>
						<div style="float:left;border-left:<?php echo $y; ?>px solid black;">
							<div style="width:100%;float:left;padding-left:3px;"><b>Terms of Payments:</b> <?php echo $ordersInfo->payment_terms; ?></div>							
						</div>
					</div>
				</div>
				
				<div  style="border-top:2px solid black;border-bottom:2px solid black;width:100%;float:left;">
					<div style="width:100%;float:left;padding-left:3px;"><b>Terms & Conditions:</b> <?php echo $ordersInfo->terms_conditions; ?></div>					
				</div>
				
				<div  style="border-top:0px solid black;border-bottom:2px solid black;width:100%;float:left;">
					<div style="width:100%;float:left;padding-left:3px;"><b>Special instruction:</b> <?php echo $ordersInfo->special_instruction; ?></div>					
				</div>
			</div>
			<div style="border:0px solid black;">	
				<div style="width:100%;float:left;">
					<table style="font-size:12px;border-collapse: collapse;">
						<tr>
							<th style="border-bottom:2px solid black;border-left:2px solid black;border-right:2px solid black;width:4%;">S.N.</th>
							<th align="left" style="border-bottom:2px solid black;border-right:2px solid black;width:47.8%;">Product Description</th>
							<th style="border-bottom:2px solid black;border-right:2px solid black;width:8%;">HSN<?php if(($ordersInfo->currency == 'INR') && ($customerInfo->country_id == '99')){ echo '-GST'; ?><?php } ?></th>
							<th style="border-bottom:2px solid black;border-right:2px solid black;width:6%;">Qty</th>
							<th style="border-bottom:2px solid black;border-right:2px solid black;width:6%;">Unit</th>
							<th style="border-bottom:2px solid black;border-right:2px solid black;width:6%;">Rate</th>
							<th style="border-bottom:2px solid black;border-right:2px solid black;width:9%;">Discount/Unit</th>
							<th style="border-bottom:2px solid black;border-right:2px solid black;width:9%;" align="right">Net Amount</th>
						</tr>
						
						<?php
							$net_total = 0;
							$i=1;
							foreach($orderProducts as $orderProduct){ 
								$net_total = $net_total + $orderProduct['net_amount'];					
						?>						
							<tr class="prtr" data-val="<?php echo $orderProduct['prod_id'];?>">
								<td align="center"  style="border-left:2px solid black;border-bottom:2px solid black;border-right:2px solid black;"><?php echo $i; ?></td>
								<td align="left" style="border-bottom:2px solid black;border-right:2px solid black;"><b> <?php echo $orderProduct['model_name']; ?> </b> | <?php echo $orderProduct['description']; ?></td>
								<td align="center" style="border-bottom:2px solid black;border-right:2px solid black;"><?php echo $orderProduct['hsn']; ?><?php if(($ordersInfo->currency == 'INR') && ($customerInfo->country_id == '99')){ echo '<br>'.$orderProduct['product_gst']; ?> %<?php } ?></td>
								<td align="center" style="border-bottom:2px solid black;border-right:2px solid black;"><?php echo $orderProduct['qty']; ?></td>
								<td align="center" style="border-bottom:2px solid black;border-right:2px solid black;"><?php echo $orderProduct['unit']; ?></td>
								<td align="center" style="border-bottom:2px solid black;border-right:2px solid black;"><?php echo number_format((float)$orderProduct['rate'], 4, '.', ''); ?></td>
								<td align="center" style="border-bottom:2px solid black;border-right:2px solid black;"><?php echo number_format((float)$orderProduct['discount'], 4, '.', ''); ?></td>
								<td align="right" style="border-right:2px solid black;border-bottom:2px solid black;"><?php echo number_format((float)$orderProduct['net_amount'], 2, '.', ''); ?></td>
							</tr>
						
						<?php $i++; } ?>
						<?php
							if(empty($ordersInfo->currency_html)){
								$ordersInfo->currency_html='<img src="'.base_url().'/assets/img/rupee.png" style="width:6px;">';
							}
						?>
						
						<tr class="nettottr" >
							<td style="border-left:2px solid black;border-bottom:2px solid black;border-right:2px solid black;" colspan="7" align="right" ><b>Net Total</b></td>
							<td style="border-right:2px solid black;border-bottom:2px solid black;" align="right"> <?php echo $ordersInfo->currency_html; ?>&nbsp; <span id="net_total"><?php echo number_format((float)$net_total, 2, '.', ''); ?></span></td>
						</tr>
						<tr class="ftr">
							<td style="border-left:2px solid black;border-bottom:2px solid black;border-right:2px solid black;" colspan="7" align="right" ><b>Freight Charges</b></td>
							<td style="border-right:2px solid black;border-bottom:2px solid black;" align="right"> <?php echo $ordersInfo->currency_html; ?>&nbsp; 
							<span id="freight_charge"><?php echo number_format((float)$ordersInfo->freight_charge, 2, '.', ''); ?></span></td>
						</tr>
								<?php
									if(($ordersInfo->currency == 'INR') && ($customerInfo->countryId == '99')){
									if($productgst){ 
									$totwithgst = 0;
									$freight_charge = $ordersInfo->freight_charge;
									$freight_gst = $ordersInfo->freight_gst;
									$flagFreightGST=1;# set 0 if GST% of freight charge is in the list of products.
									#i.e to cheate the row for GST @ 18% (Freight GST)
									foreach($productgst as $progst){
									/* $perProFrch = ($freight_charge / $net_total) * $progst['net_amount'];
									$perProFrchWthGst = ($perProFrch * $progst['product_gst']/100);
									$totgst = $perProFrchWthGst + ($progst['net_amount'] * $progst['product_gst']/100);
									$totgst = number_format((float)$totgst, 2, '.', '');
									$totwithgst = $totwithgst + $totgst; */
									$perProFrchWthGst=0;
									if($freight_gst==0){
											$perProFrch = ($freight_charge / $net_total) * $progst['net_amount'];
											$perProFrchWthGst = ($perProFrch * $progst['product_gst']/100);
										}else if(!empty($freight_gst)){
											if($freight_gst==$progst['product_gst']){
												$perProFrchWthGst = ($freight_charge * $freight_gst)/100;
												$flagFreightGST=0;
											}
										}

										$totgst = $perProFrchWthGst + ($progst['net_amount'] * $progst['product_gst']/100);	
										$totgst = number_format((float)$totgst, 2, '.', '');
										$totwithgst = $totwithgst + $totgst;
								?>
							
								<tr style="border-top:2px solid black;">
									<td style="border-left:2px solid black;border-bottom:2px solid black;border-right:2px solid black;" colspan="7" align="right" ><b>GST @ <?php echo $progst['product_gst']; ?>%</b></td>
									<td style="border-right:2px solid black;border-bottom:2px solid black;" align="right"> <?php echo $ordersInfo->currency_html; ?>&nbsp; <?php echo number_format((float)$totgst, 2, '.', ''); ?></td>
								</tr>
							<?php } ?>
							
							<?php if($flagFreightGST==1 && $freight_gst>0){ 
											$perProFrchWthGst = ($freight_charge * $freight_gst)/100;
											$totgst = $perProFrchWthGst;
											$totgst = number_format((float)$totgst, 2, '.', '');
											$totwithgst = $totwithgst + $totgst;
										?>
											<tr>
												<td style="border-left:2px solid black;border-bottom:2px solid black;border-right:2px solid black;" class="border_right border_top" colspan="7" align="right" ><b>GST @ <?php echo $freight_gst; ?>%</b></td>
												<td style="border-right:2px solid black;border-bottom:2px solid black;" class="border_right border_top" align="right"> <i class="<?php echo $ordersInfo->currency_faclass; ?>" style="font-size:13px;"></i>&nbsp; <?php echo number_format((float)$totgst, 2, '.', ''); ?></td>
											</tr>
										<?php } ?>
							
							
							<?php } ?>
							<?php } ?>
						<tr class="grndtr" style="border-top:2px solid black;">
							<td style="border-left:2px solid black;border-bottom:2px solid black;border-right:2px solid black;" colspan="7" align="right" ><b>Grand Total</b></td>
							<td style="border-right:2px solid black;border-bottom:2px solid black;" align="right"><b> <?php echo $ordersInfo->currency_html; ?>&nbsp; <span id="grand_total"><?php echo number_format((float)($net_total + $ordersInfo->freight_charge + $totwithgst), 2, '.', ''); ?></span> </b></td>
						</tr>
					</table>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-sm-12" style="padding-right: 0px;padding-left: 0px;">
					<p style="margin: 0px;">Greetings!<br>
Thank you for your valued order. Same is under process. We request you to please check all the details as above and arrange payment as per banking details below. In case you wish to use online payment , please use our payment gateway at our website <a href="http://www.optitecheyecare.com/payment.php">www.optitecheyecare.com/payment.php</a> .</p> 
					<p style="margin: 0px;"></p>					
				</div>					
			</div>
				<br>
				<div class="row">
				
					<div class="col-sm-12" style="width:100%;padding-right: 0px;padding-left: 0px;">
						<p style="margin: 0px;">Remit to:</p>								
					</div>
					
					<div class="col-sm-6" style="width:50%;float:left;padding-right: 0px;padding-left: 0px;">				
						<div style="width:100%;float:left;">
							<p style="margin: 0px;width:40%;float:left;"><b>Payment :</b></p><p style="margin: 0px;float:left;">100% T/T(wire)</p>
						</div>
						<div style="width:100%;float:left;">
							<p style="margin: 0px;width:40%;float:left;"><b>Beneficiary's Name :</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->beneficiary_name; ?></p>
						</div>
						<div style="width:100%;float:left;">
							<p style="margin: 0px;width:40%;float:left;"><b>Bank Name :</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->bank_name; ?></p>
						</div>
											
					</div>

					<div class="col-sm-6" style="width:48%;float:right;padding-right: 0px;padding-left: 0px;">
						<div style="width:100%;float:left;">
							<p style="margin: 0px;width:40%;float:left;"><b>Bank Details for :</b></p><p style="margin: 0px;float:left;"> (<?php echo $ordersInfo->currency; ?>)</p>
						</div>
						<div style="width:100%;float:left;">
							<p style="margin: 0px;width:40%;float:left;"><b>Account No. :</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->account_number; ?></p>
						</div>
						
						<?php if($ordersInfo->currency == 'INR'){ ?>
							<?php if(!empty($bankInfo->ifsc_code)){ ?>
							<div style="width:100%;float:left;">
								<p style="margin: 0px;width:40%;float:left;"><b>IFSC Code :</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->ifsc_code; ?></p>
							</div>
							<?php } ?>
						<?php } else { ?>
							<?php if(!empty($bankInfo->swift_code)){ ?>
							<div style="width:100%;float:left;">
								<p style="margin: 0px;width:40%;float:left;"><b>SWIFT Code :</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->swift_code; ?></p>
							</div>
							<?php } ?>
						<?php } ?>				
					</div>	
					
					<div class="col-sm-12" style="width:100%;float:left;padding-right: 0px;padding-left: 0px;">				
						<div style="width:100%;float:left;">
							<p style="margin: 0px;width:20%;float:left;"><b>Bank Address :</b></p><p style="margin: 0px;float:left;"> <?php echo $bankInfo->bank_address; ?></p>
							<p style="margin: 0px;color:red;"><b>Bank remittance charge shall be paid by payer(buyer)</b></p>
						</div>									
					</div>
				
				
					<div class="col-sm-12" style="padding-right: 0px;padding-left: 0px;">						
						<p style="margin: 0px;">For Tarun Enterprises</p><br><br>
						<p style="margin: 0px;">Order Processing Team</p><br>
						<!-- <p style="margin: 0px;font-size:11px;">Created by (<?php echo $ordersInfo->firstname .' '.$ordersInfo->lastname; ?>)</p> --> 
					</div>					
				</div>
		
</div>
<div style="padding-right: 25px;padding-left: 25px;font-size:12px;">
	<div class="col-sm-12" style="width:100%;float:left;padding-right: 0px;padding-left: 0px;font-size:11px;">				
		<div style="width:100%;float:left;">
			<p style="margin: 0px;float:left;">This is a computer-generated document. No signature is required.</p>
		</div>									
	</div>
</div>
<?php
function after ($inthis, $inthat)
{
	if (!is_bool(strpos($inthat, $inthis)))
	return substr($inthat, strpos($inthat,$inthis)+strlen($inthis));
}
?>